### ISSUE TITLE
Silent Config no longer works with version 19.086.0502.0006

### ISSUE THREAD

**Issue by JWCC-john** [MicrosoftDocs/OfficeDocs-SharePoint#1105]
Was working fine up until last week sometime when our machines started updating to 19.086.0502.0006

Now users are prompted to login when opening Onedrive for the first time

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a21a400-6ad2-b371-0205-9a1b51b3fe29
* Version Independent ID: 801d184f-046b-8d37-30f7-f82ebda3df3f
* Content: [Silently configure user accounts](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration#feedback)
* Content Source: [OneDrive/use-silent-account-configuration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-silent-account-configuration.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@JWCC-john thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Paddy834u** [comment]
1) Is this expected behavior? or it should automatically sign in without even entering user name?
 According to this post, we have to enter user name, not password
https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration
To test single sign-on, run OneDrive setup using the /silent parameter and enter your user name. Setup should not prompt for credentials. 

 According to this post, without entering any credentials (user name or password) 
 https://docs.microsoft.com/en-us/onedrive/use-group-policy#SilentAccountConfig 
 If you enable this setting, users who are signed in on a PC that's joined to Azure AD can set up the sync client without entering their account credentials. 

2) Is Silent set up supported in Hybrid domain joined PCs?
 According to this post, they have referred to Azure AD
 https://docs.microsoft.com/en-us/onedrive/use-group-policy#SilentAccountConfig 
 If you enable this setting, users who are signed in on a PC that's joined to Azure AD can set up the sync client without entering their account credentials. 

 According to this post, 
 https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration 
 If you have an on-premises environment that uses Active Directory, you can enable hybrid Azure AD joined devices to join devices on your domain to Azure AD

**Comment by jgwinner** [comment]
It's a mess.

**Comment by loosus456** [comment]
I would like to know if this is still a supported feature.  This is *literally* why these documents exist. 
 But @scanum closes the issue without addressing the question.  I am guessing this person is required to meet a monthly quota of closed issues, even if the issues are not addressed.

**Comment by jgwinner** [comment]
This is still a badly broken product.

I had to pay a guy to run around and fix the problem on 50 machines. This is exactly why Group Policy exists; yet One Drive for Business just doesn't work at all without manual intervention

Closing the ticket without any comments is a problem too.

THIS IS NOT FIXED.
