### ISSUE TITLE
When, pointing to personal OneDrive, Document Library field is blank

### ISSUE THREAD

**Issue by DougPunchak** [MicrosoftDocs/OfficeDocs-SharePoint#114]
When I point the tool to someone's OneDrive for business, the document library field is empty and doesn't allow me to continue.  How do I get it to see that their OneDrive IS the document library?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36d01d11-eea9-7f49-693d-25c3fecc6253
* Version Independent ID: 6749a619-2b75-1561-81e9-b45888c58c4b
* Content: [How to use the SharePoint Migration Tool](https://docs.microsoft.com/en-us/sharepointmigration/how-to-use-the-sharepoint-migration-tool)
* Content Source: [migration/how-to-use-the-sharepoint-migration-tool.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-use-the-sharepoint-migration-tool.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by kenwith** [comment]
@DougPunchak - sorry for the delay on this and that it has taken some time to see it in this documentation issues list. I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. They will prioritize and figure out the root cause.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
