### ISSUE TITLE
Can you also include the "Restricted View" permission level description? 

### ISSUE THREAD

**Issue by Sahenriq** [MicrosoftDocs/OfficeDocs-SharePoint#1307]
I can't find a "Restricted View" permission level description in any documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f072d4a-23e6-d73f-397e-4ffc000570a9
* Version Independent ID: 1ee08317-82cd-9f23-a1e9-d2380fb7ff78
* Content: [Understanding permission levels in SharePoint](https://docs.microsoft.com/en-us/sharepoint/understanding-permission-levels#feedback)
* Content Source: [SharePoint/SharePointOnline/understanding-permission-levels.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md)
* Product: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@Sahenriq  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dplotnikov** [comment]
@Sahenriq it's there actually but I see what you are saying. There is a rendering limitation on docs because of the width, so you should scroll right and you'll see what you are looking for. Specifically, I'm talking about tables in these 2 sections - Site permissions and permission levels and List permissions and permission levels

**Comment by dplotnikov** [comment]
@Sahenriq and @Rafaesp do you guys still have any questions about it?

**Comment by Rafaesp** [comment]
@dplotnikov the docs says that `View only` allows to `View Items` but if I use that level, I'm not able to see pages like the root `Home.aspx` of a site. I am able to view a Word document but not to download it. What permission denies the download a document? I mean, am I able to copy the behaviour of `View only` just by creating a new custom permission level? I don't think so.

**Comment by dplotnikov** [comment]
@Rafaesp `View Only` doesn't allow you to download documents but I see that you have a lot of custom permissions and we are talking here just about documentation and not your custom permission levels here.

**Comment by Rafaesp** [comment]
@dplotnikov I don't have any custom permission levels.
One of my questions is:
In this table https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/understanding-permission-levels.md#list-permissions-and-permission-levels, which set of permissions do I have to set in order to deny the download of a document as the `View Only` level does?

**Comment by dplotnikov** [comment]
@Rafaesp it will work just for `View Only`

**Comment by Rafaesp** [comment]
So, is View Only using undocumented permissions? When using the API, View
Only seems to return more permissions than the ones documented here.

**Comment by dplotnikov** [comment]
I think it's using some IRM related permissions

**Comment by Rafaesp** [comment]
I'll have a look. Thanks.

**Comment by scanum** [comment]
@Sahenriq Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
