### ISSUE TITLE
A table of service account app pools and their accounts

### ISSUE THREAD

**Issue by eschrader** [MicrosoftDocs/OfficeDocs-SharePoint#135]
Hi, it would be nice to have a table summary of the service account app pools and the respective service account recommendations. For example, Managed Metadata would run under x service application pool using x account as a recommendation for a least privileges security install

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c73d53bc-485a-a5d8-d864-e2e402c07625
* Version Independent ID: 72edd383-b5cb-3b66-4fb2-e9f5ab7d56ce
* Content: [Account permissions and security settings in SharePoint Server 2016](https://docs.microsoft.com/en-us/sharepoint/install/account-permissions-and-security-settings-in-sharepoint-server-2016)
* Content Source: [SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/install/account-permissions-and-security-settings-in-sharepoint-server-2016.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by tseward** [comment]
I'll be taking a pass on this document, but it will be very simple:

All Service Applications belong to a single Application Pool run by a single account. Same goes with Web Applications. Services such as Search and App Fab run under the same service account as Service Applications.

C2WTS is the only exception in that it gets a dedicated account.

**Comment by eschrader** [comment]
I guess I mean what accounts (network service, etc.) Run sharepoint web services default, search app pool, etc. For a best practice on least privlages security.



Sent via the Samsung Galaxy S7 active, an AT&T 4G LTE smartphone

**Comment by tseward** [comment]
There aren't many defaults (sans the Windows Services related to Search and AppFab which are going to default to the Farm Admin account).

The minimal number of accounts/Application Pools significantly improves performance and reduces memory usage. I did testing quite some time ago on this at https://thesharepointfarm.com/2014/08/expense-application-pools/.

We can still follow least priv and even security such as preventing interactive logon with those accounts. I can certainly outline that, as well.

While there might be a sense of additional security with say an account per Service Application (thus Application Pool), it doesn't truly exist given the databases each service account has access to.

**Comment by ToddKlindt** [comment]
Here is a list of the service accounts I use, and what they do, https://www.toddklindt.com/blog/Lists/Posts/Post.aspx?ID=391 It's mostly in line with what @tseward says. Like him, I run as few app pools as possible, and I also configure everything as least privileges.

**Comment by harbars** [comment]
Having multiple accounts per endpoint increases risk.

It's all very simple.
Farm Account
Services Account - for every service application endpoint and windows service (including Search and DC)
Content Account - for web applications
Cache Admin
Cache Reader
Content Access - for search crawl as per requirements
If needed, and hopefully not, account for C2WTS

And they should all be regular domain accounts. At least once it comes to post deployment.

"Best practice" for "least privilege" with SharePoint is entirely impossible due to constraints and issues with the management APIs and product design. You cannot make SharePoint least privilege because the product isn't designed to meet that goal. Various operations must take place under the context of both a farm account (not a farm admin) and machine admin. We should all stop using "least privilege" as a way to describe a deployment. 

However the above is the best compromise towards- all assuming that's it configured correctly. And there in lies the rub, it's not so much about how many/which accounts, but the way and order in which they are configured? Especially when it comes to farm level and search level settings.

For example, how many customers fix up Farm admins during an install? How many govern logging and Shell Admins, etc etc? we know this is the actual gap. the accounts themselves "the least privilege you can get away with", is trivial in comparison.

**Comment by eschrader** [comment]
That’s helpful. If you list out super reader/user accounts, why wouldn’t you list out UPS with the replicate directory changes? I thought maybe you were just listing service app pool accounts but since you listed the cache accounts it looks more like you listed all service accounts and where noted their associated service application pools (and even web application pools) . I didn’t think about rolling UPS service application pool into Services Pool with Search and DC but will do.

For a slightly different topic, web application pools, would you recommend (best practice and least privilege 😊) to have MySites and the other web applications share the same app pool (not just service account, but actually the same app pool)? I remember something a while back about splitting these out so someone with SCA in their MySite cannot compromise other site collections/web applications by sharing the pool context. Pretty sure that was all “in theory” but I remember some recommendation about 5 years ago about that being pushed a bit hard.

**Comment by harbars** [comment]
Fair Point. The account used to import from AD would be another one, albeit not really a service account per se.  The cache accounts should always be included as they are required and impact multiple things inside SharePoint (e.g. web app policy) - whereas the sync account does not (it's external to sharepoint, and some customers don't perform sync with UPS or ADI).

Yes, in general, unless there is a business requirement (usually an out of date security policy with zero tangible security benefit) all web applications should be hosted in a single app pool, and therefore the same account.  You will get better performance. The only true benefit of using separate accounts is to be able to see in Task Manager which process is being run up, or to make it easier to attach a debugger. but one can easily find a PID by the name of the app pool with a single line of powershell, so that's a moot point.

Previous guidance from years back (performance characteristics differ between mysites and collaboration sites) was always total claptrap and never based on security, but theoretical performance metrics never proven with any data by any one! It was bogus advice, hence why the guidance has changed.  The stuff about supposed security isolation is also claptrap. SCA has zero impact here. If you have the ability to compromise an app pool, you own the box by being able to get the farm account. It's game over at that point, and separating things out thus provides zero tangible security benefit, decreases performance and throughput and increases complexity.

Complexity is the enemy of security.

Remember also SPO runs everything in a single web application and therefore a single app pool, and therefore a single account.  Not that i'm recommending necessarily a single web app. there are issues with that. but in terms of accounts, you want (if you can do it) to have all web apps (preferably only two) in a single app pool.

**Comment by kenwith** [comment]
I have captured all of this and will look for any PR but will also get this onto the backlog for the writing team. Thanks all.
