### ISSUE TITLE
The application will exit because of sign-in failure. Please double-check and try again.

### ISSUE THREAD

**Issue by 1986prasad** [MicrosoftDocs/OfficeDocs-SharePoint#1473]
I get the error below repeatedly even if i provide the right credentials. 

![image](https://user-images.githubusercontent.com/54548765/67751686-91febb80-fa57-11e9-97e4-35529bc48de9.png)

**Comment by scanum** [comment]
@1986prasad thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by Joesmithessang** [comment]
I think this issue is unique to tenants set up using proxy with a pac file.

The latest build version of the SPMT is rolled out with a config file that has the code segment commented out, that would allow the login of such tenant account.

Open the file location of the SPMT as downloaded on your machine, open with notepad the config file named after the executable file, scroll down to the end of the code segment and "un-comment" the commented part.

Save changes to file and re-run migration tool.
