### ISSUE TITLE
Conditional Access support

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/OfficeDocs-SharePoint#1559]
Does the sync engine supports all CA features, such as sign in risk? Or just location and device based configs? In our lab, the user does not get prompted for MFA when the risk level is raised. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app for Windows](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@BakkerJan Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by BakkerJan** [comment]
@scanum, any update on this? I ran some tests, and it seems that Onedrive Sync engine SSO does not work once MFA is active. Also, no userprompt is shown. In the Windows 10 logs – Application and Services Logs – Microsoft – Windows – AAD  I see this error:  0xcaa2000c the request requires user interaction . This is expected behaviour, since I use CA to prompt for Onedrive, but it breaks my KFM setup and Silent login. I would make more sense that the user is prompted for MFA, and then the flow continues....

**Comment by VLG17** [comment]
@BakkerJan The OneDrive sync app supports device and location based conditional access policies.

Regarding your issue, i would advise [opening a support ticket](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.onedrive), so a support engineer can look into this. MFA should not break the Known Folder Move sync/process. 

Do you mean [this](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration) with Silent Login, or something else like SSO? I'm asking because for "silently configure user accounts" it's specified that:

**"Silent account configuration won't work on devices for users who require multi-factor authentication."**

**Comment by BakkerJan** [comment]
> @BakkerJan The OneDrive sync app supports device and location based conditional access policies.
> 
> Regarding your issue, i would advise [opening a support ticket](https://support.office.com/en-us/home/contact?contactUsExperienceEntryPointAssetId=S.HP.onedrive), so a support engineer can look into this. MFA should not break the Known Folder Move sync/process.
> 
> Do you mean [this](https://docs.microsoft.com/en-us/onedrive/use-silent-account-configuration) with Silent Login, or something else like SSO? I'm asking because for "silently configure user accounts" it's specified that:
> 
> **"Silent account configuration won't work on devices for users who require multi-factor authentication."**

Thanks for pointing out @VLG17 , the note must be added after I looked into this problem. This behaviour is what I had seen in my lab.

**Comment by j0rt3g4** [comment]
@BakkerJan  Added the note in the PR #1690  @scanum
