### ISSUE TITLE
Cannot  reuse URL and cannot change back

### ISSUE THREAD

**Issue by robertafreese** [MicrosoftDocs/OfficeDocs-SharePoint#1575]
It was not clear that the URL was not released, it was going to be a redirection. Is there a way to change it back? It will not change back and there is no error, it just will not allow it. The box has a red outline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5475fd83-52fa-6d49-d08f-fc75fabee09c
* Version Independent ID: 19ede247-e62c-9f1a-700c-4c878fec7f78
* Content: [Change a site address (preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/change-site-address#feedback)
* Content Source: [SharePoint/SharePointOnline/change-site-address.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/change-site-address.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by JeremyEsposito** [comment]
As part of changing a site address, moving a site to a different geo location, or swapping a site, we automatically create redirects to ensure that links pointing to the prior URL continue to work. These redirects are sites that use a special site template at the prior site URL.
For example, if you changed a site address from https://contoso.sharepoint.com/sites/OldSiteName to https://contoso.sharepoint.com/sites/NewSiteName or moved a site from https://contoso.sharepoint.com/sites/SiteName to https://contosoEUR.sharepoint.com/sites/SiteName, we'll place a redirect (Template type REDIRECTSITE#0) at the old URL, which contains special headers and logic to redirect your browser requests to the new site.
In order to re-use the old URL from a new site, you will need to delete the redirect.
This document contains the details/cmd's to delete the redirect.
https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects

**Comment by robertafreese** [comment]
The linked solution requires PowerShell, which I don't use, but thanks, at least it shows that it may be possible someday to do this from the administration portal. I have tried several times to install it, including today and it just throws errors that, 
 The specified module 'Microsoft.Online.SharePoint.PowerShell' was not loaded because no valid module file was found in any module directory.

 I know this is not the place to get help with that, and I will just hope that someday there is a way to do this in the administrative portal. If there is a User Voice request, I will vote for it.

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@robertafreese 
You can install it using any of these 2 methods

# Direct download
https://www.microsoft.com/download/details.aspx?id=35588

# Using Powershell on a Win10 machine
- Open up Powershell as an administrator, then run:
````Powershell
Set-ExecutionPolicy RemoteSigned
#Accept with "A" and "Enter"
Install-Module -Name Microsoft.Online.SharePoint.PowerShell -AllowClobber
Connect-SPOService
#add global admin username and password or /username and App password if you have MFA enabled
Remove-SPOSite -Identity https://contoso.sharepoint.com/sites/OldSiteName
```
Source:
https://docs.microsoft.com/en-us/sharepoint/manage-site-redirects

**Comment by scanum** [comment]
@robertafreese Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
