### ISSUE TITLE
Migration Speeds - Package the Content Section

### ISSUE THREAD

**Issue by obhayes** [MicrosoftDocs/OfficeDocs-SharePoint#1729]
In the section where you provide estimates of the type of migration speeds you may achieve, i feel the information is a bit misleading as it talks about the "Maximum speed". In reality what is the "expected speed" customers can expect based on prior stats?  For example, maybe 6 months ago, using SPMT or migration tools from 3rd parties i could see a throughput of 5-10GB per hour into SharePoint Online,, recently i am experiencing closer to 3GB an hour to get data into SPOnline (this is using azure storage prior to import to avoid SPO throttling). So in a day i would say for medium type of data (office files 1.5mb) its more like 72GB not 1000GB. It is even some way off the 250GB max for small files. So any chance of an expected migration speed column being added? Likewise the migration time is really split into 2 (your internet connection speed/bandwidth) and the speed in which the data is ingested into shareopint / MS Teams from Azure, which there appears to be no metrics on. I.e. a customer can address their network speeds /bandwidth but their hands are tied at the azure import-&gt;SharePoint. It makes it very hard to have discussions with customers on how long this will take with big unknowns and lack of visibility.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28ed221a-ca52-7a6a-4b89-1417066ffcbd
* Version Independent ID: e7fdb3a0-c148-85d1-48cf-57998d190a8a
* Content: [General migration performance guidance - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sharepoint-online-and-onedrive-migration-speed#feedback)
* Content Source: [migration/sharepoint-online-and-onedrive-migration-speed.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sharepoint-online-and-onedrive-migration-speed.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by tseward** [comment]
Expected would be too scenario-specific with too many factors to provide a reliable number. Yes, it is filled with unknowns. Since the conditions on the Azure -> SPO/ODfB are automatically throttled based on resource usage in the stamp, available bandwidth, possible service issues, among other factors, providing a hard and fast guide would be virtually impossible.

Unfortunately that is just how SPO migrations go. The best thing you can do for customers is to perform that initial full which will outline a _very rough approximation_ of how long a migration will take. The iterative migrations after the initial full will in general be much faster given low data churn on the source.

**Comment by scanum** [comment]
@obhayes Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
