### ISSUE TITLE
OneDrive

### ISSUE THREAD

**Issue by robertcaretta** [MicrosoftDocs/OfficeDocs-SharePoint#1885]
Can this tool migrate file share content to work OneDrive accounts?
https://danfoss-my.sharepoint.com/personal/username_company_com/_layouts/15/onedrive.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08bbc47b-020e-8837-3f2f-f2911eec8476
* Version Independent ID: 7d392968-5ee9-7fab-323f-98cd54097fd3
* Content: [Migration Manager FAQs - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs)
* Content Source: [migration/mm-faqs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-faqs.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@robertcaretta thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by stalks** [comment]
I'd also like this answered. I don't expect to be told to go find out the info myself when submitting feedback to the document that should answer this question.

**Comment by cabtilx** [comment]
This is a FAQ page and robertcaretta asked what is I suspect a very frequently asked question.
@scanum  Product capabilities are not part of the remit of support.  This isn't an incident or troubleshooting request. It is related to the features of the product which should be documented within these support pages. You should be ashamed for such an unhelpful copy+paste response, that is also not the role of you on these pages!

@robertcaretta + @stalks - Yes the Migration Manager tool can migrate to: a SharePoint site, OneDrive or Teams location
It is not documented here (most likely because people like scanum do not understand that this is their role) but you can see it within the Migration Manager wizard.

![image](https://user-images.githubusercontent.com/39379796/82337288-82d75f00-99e3-11ea-8164-2e4383465cd7.png)

**Comment by ric-HTS** [comment]
can i use JSON or csv to mass migrate data from user folders in sharepoint to their onedrive in the same tenant?

source : sharepoint/folder
destination onedrive_user/folder
