### ISSUE TITLE
B2B OTP replacing the the ad-hoc external sharing experience used in OD4B/SPO

### ISSUE THREAD

**Issue by tfurstms** [MicrosoftDocs/OfficeDocs-SharePoint#1917]
Hello- Thanks for this article! I had a question on following statement, "After preview, this feature will replace the ad-hoc external sharing experience used in OneDrive and SharePoint today for all tenants."

Question -&gt; Since the B2B OTP will replace the the ad-hoc external sharing experience used in OD4B/SPO, can you put a placeholder in this article that will link to the future guidance on how this transition will need to managed by customers. Every customer that I talk to about this starts asking about "how" the transition will occur. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 71747405-a38b-c475-7915-bb10242b689f
* Version Independent ID: ccf67a68-63d7-9d04-69c7-728fabb3be24
* Content: [SharePoint and OneDrive integration with Azure AD B2B (Preview) - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/sharepoint-azureb2b-integration-preview)
* Content Source: [SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharepoint-azureb2b-integration-preview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@MSFTRafLop can you comment?

**Comment by MSFTRafLop** [comment]
For the most part, customers don't need to re-share content that was already shared externally. Just like when you enable the preview. The reason is that when an "old" link is clicked again then we create a B2B Invite on-demand in that moment on behalf of the user who originally created the "old" link. There are instances where this on-deman B2B Invite won't work, like if it conflicts with an AAD B2B policy or if the user who created the "old" link no longer is at the company or no longer has permission to share or create B2B invitations.

**Comment by scanum** [comment]
@tfurstms Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
