### ISSUE TITLE
Converting copied Library ID from Unicode to ASCII - Is it really Necessary?

### ISSUE THREAD

**Issue by mbenadiba** [MicrosoftDocs/OfficeDocs-SharePoint#1941]
Hello.
I have been able to successfully push Team Sites for the last few months using the GPO item "Configure team site libraries to sync automatically" without converting the Unicode charactars to ASCII charactars.  I have visited this article page several times over the last year and do not recall this requirement. 
As of a few days ago, i am successfully able to push document libraries to computers, but I have noticed some computers are not receiving the most recent push of Document libraries.

Can you confirm if this is a brand new requirement, that the string copied from SharePoint "Sync" button must now be converted to ASCII?  If so, must we go back and reconfigure previously configured GPOs to use ASCII charactars only, and is there a version number for OneDrive.exe that we should be aware of where this behaviour has changed?
Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#feedback)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@mbenadiba 
thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by nikmanzotti** [comment]
I was wondering the same, and it seems I'm not alone (see #323).

@scanum unfortunately, due to the current situation, the Support team has been quite busy lately and their response times are long. I think it would be better not to bother them with this kind of questions which it's unlikely they will able to solve directly.

I've started a [new conversation on the Tech Community](https://techcommunity.microsoft.com/t5/forums/postpage/board-id/OneDriveforBusiness/attachments-key/dd69bfb9-10de-4c60-8d26-60b41631f5fc), and maybe @SteveHosko and @thwpike who edited the docs to add this step can provide us with useful insight!
