### ISSUE TITLE
Location based control vs. conditional access policy

### ISSUE THREAD

**Issue by jonwbstr** [MicrosoftDocs/OfficeDocs-SharePoint#1973]
Hello,
Would you include something in this article that talks about Conditional Access. Conditional Access has an extra license requirement. It would be useful if this page answered the following questions,

If we are using conditional access should we also setup a sharepoint location based policy as well because they work differently?

Or, 
A conditional access policy accomplishes the same thing that a location based policy acomlishes and if we have a conditional access policy, we do not need a sharepoint location based policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4128fad9-2907-9f45-592f-2336dbd25ee3
* Version Independent ID: 6e105343-1f95-c061-dc48-187c2fb6870d
* Content: [Network location-based access to SharePoint and OneDrive - SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location)
* Content Source: [SharePoint/SharePointOnline/control-access-based-on-network-location.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/control-access-based-on-network-location.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by lindspea** [comment]
@jonwbstr Thank you for reaching out and helping improve MS Docs. This article has also been updated recently, so please let me know if you still need help. Here is another page to have a look at - https://techcommunity.microsoft.com/t5/azure-active-directory-identity/conditional-access-8220-limited-access-8221-policies-for/ba-p/245228.

**Comment by scanum** [comment]
@jonwbstr Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by o365tatsuyan** [comment]
@scanum 
I believe the "[access control from unmanaged devices](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)" requires an AAD Premium license, but I don't think this "[access control based on network location](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location)" requires an AAD Premium license. It should work without AAD premium license.
Hence, I would recommend to delete this "important" notice" from [this ](https://docs.microsoft.com/en-us/sharepoint/control-access-based-on-network-location) document, it makes customer to confuse.

Further info, this document doesn't mention this "Access control: network location" requires AAD Premium license.
https://docs.microsoft.com/en-us/office365/servicedescriptions/sharepoint-online-service-description/sharepoint-online-service-description#security-and-compliance-features
--------------------------
Security and compliance features
Unless otherwise noted, the following features are available across all plans that include SharePoint, and all SharePoint standalone plans:
Access control: network location
Access control: unmanaged devices. Requires Azure AD Premium P1.
--------------------------
