### ISSUE TITLE
More explanation of the JSON file format needed

### ISSUE THREAD

**Issue by MrNigel** [MicrosoftDocs/OfficeDocs-SharePoint#2226]
I am referring to the section: **Using a JSON file for data content migration**.

It is clear from the example that there are more config options available via the JSON file than in the .csv format file.  However, unlike the detailed explanation of the .csv options there is no detailed description for the JSON option.  Please could you provide the detail text for ALL the Settings:

Settings": {

        "MigrateHiddenItems": true,
        "MigrateItemsCreatedAfter": "2016-05-22",
        "MigrateItemsModifiedAfter": "2016-05-22",
        "SkipFilesWithExtensions": "txt:mp3",
        "FilterOutPathSpecialCharacters": false,
        "MigrateOneNoteNotebook": true
      }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7331acc8-e10a-d41b-2f8d-0bc991987f3c
* Version Independent ID: e42887fd-650c-259d-706a-635eacc08a76
* Content: [How to format a CSV or JSON file for bulk upload in Migration Manager - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json)
* Content Source: [migration/mm-bulk-upload-format-csv-json.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/mm-bulk-upload-format-csv-json.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@MrNigel Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by scanum** [comment]
@JoanneHendrickson Following up on this issue. Thanks!

**Comment by JoanneHendrickson** [comment]
Will update

**Comment by Pentao** [comment]
It would be great if you guys could clarify on the use of the parameter `"FilterOutPathSpecialCharacters"`.
I did try to set the switch of `true` and run it. 
But as I don't know what would be the parameter to specify what character to use to replace any illegal characters, it just doesn't seem to do anything?
 
It is nice that if you just provide a `"TargetListRelativePath"~ it just creates it, it's not documented but with trial and error you can discover it. 

```JSON
{

    "Tasks": [
  
      {
        "SourcePath": "\\\\192.168.1.1\\Share\\Data\\JSON Test",        
        "TargetPath": "https://singergroup.sharepoint.com/sites/IT",
        "TargetList": "Archived Data",
        "TargetListRelativePath": "JSON Test",
  
        "Settings": {
  
          "MigrateHiddenItems": true,
          "FilterOutPathSpecialCharacters": true,
          "MigrateOneNoteNotebook": true
        }
      }
    ]
  }
```

**Comment by JoanneHendrickson** [comment]
Researching your questions -- will get back to you as soon as I hear.  Good question!

**Comment by JoanneHendrickson** [comment]
Hi @Pentao  - The parameter **"FilterOutPathSpecialCharacters"** is a deprecated feature, and has now been replaced by the It is replaced by replace-invalid-chars which can be set in the task creation settings panel. 

Can you explain a little further regarding your suggestion about the "TargetListRelativePath"? This was a parameter you discovered that works?

**Comment by pete-k-0** [comment]
Hi, I'm trying to submit a json file for a batch of as part of a OneDrive file migration, however the settings specified for the first user are applying to the entire batch. For example, I specify a different MigrateItemsModifiedAfter for each user but it is picking it from the first user only and applying the entire batch. I need to submit the batch with a different MigrateItemsModifiedAfter date for each user as this is a clean-up delta migration only - please could someone advise why this does not work with the json input?

**Comment by ukdocCT** [comment]
@scanum  @JoanneHendrickson Is there any progress on this as it has been two years since it was raised?
Although the spmt documentation in [https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2226#issuecomment-815038705](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2226#issuecomment-815038705) was useful it still does not make reference to parameters that potentially are possible from the GlobalSettings.csv file that gets exported when a migration is run.
For example the following fields would be useful to know that the field reference would be in the JSON:
Keep all versions,False
Automatic user mapping,True
Only Perform Scan,False
Start Migration If No Scan Issue,False
Preserve Permission Inheritance,False

**Comment by JulLeuverink** [comment]
@scanum @JoanneHendrickson I don't feel like this Issue is solved. 
There is still no explanation for the JSON properties. You can find some usage examples [here](https://learn.microsoft.com/en-us/powershell/module/spmt/add-spmttask?view=spmt-ps) and [here](https://learn.microsoft.com/en-us/sharepointmigration/mm-bulk-upload-format-csv-json) but they are neither described nor complete. For example the "settings" property is missing "Temporarily allow migration of scripts" and many others.
