### ISSUE TITLE
Internal URLs do not support HTTPS

### ISSUE THREAD

**Issue by achimismaili** [MicrosoftDocs/OfficeDocs-SharePoint#231]
It seems to me, that internal URLs do not support SSL configuration.
In case, an internal URL is configured with SSL, it does not return the page of the public URL, instead it returns a 302 redirect to the public URL. :/

Therefore, I think, it is a missleading example in this documentation, to say: 
"Add internal URL ... (for example, https://www.fabrikam.com)"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 20c155b1-6a8e-574d-0677-27b37d24caf4
* Version Independent ID: c5e56cee-22d1-0725-eb7f-280391e2b692
* Content: [Configure alternate access mappings for SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/configure-alternate-access-mappings)
* Content Source: [SharePoint/SharePointServer/administration/configure-alternate-access-mappings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/configure-alternate-access-mappings.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @Techwriter40
* Microsoft Alias: **kirks**

**Comment by AndreaBarr** [comment]
@achimismaili - Thank you for submitting this feedback.

Thank you for pointing out the URL situation here. I will make sure this gets to the SharePoint team so that we can get this properly addressed.

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by achimismaili** [comment]
Hello Andrea, I am very sorry, it turned out that the 302 is caused by JavaScript in the browser, not by the web server response. So, I was wrong, SharePoint DOES support HTTPS in case of internal AAM URLs.
If it is possible, please cancel your notification to the SharePoint team.
Sorry again for the inconvenience.

**Comment by AndreaBarr** [comment]
@achimismaili Thank you for the update on this. I will cancel my notification and close this issue.
