### ISSUE TITLE
PowerShell script for this report

### ISSUE THREAD

**Issue by Kasstriot** [MicrosoftDocs/OfficeDocs-SharePoint#2352]
We find this report very useful and would like to build a dashboard which updates on regular basis, therefore it would be very helpful if you can share a PowerShell script on how to run it. 

Thank you
Kastriot

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6b3a83b-6891-2c36-671b-e3d634aa051c
* Version Independent ID: 705c5543-5e3c-d16d-8014-63739c88483b
* Content: [Report on sharing - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharing-reports)
* Content Source: [SharePoint/SharePointOnline/sharing-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/sharing-reports.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by MikePlumleyMSFT** [comment]
@StephenRiceMSFT any PowerShell option for the sharing reports?

**Comment by StephenRiceMSFT** [comment]
Not at this time. Something the team is exploring & looking at though.

**Comment by Jmartinez589** [comment]
Thanks for the update. The reason it would be helpful to have PowerShell options is that the UI is quite limited. Meaning the customer has a list of shared folders. I didn't count but more than 40 and it appears that the UI for this option is limited to only a certain number of folders. We can not scroll down any further to see his folder. And when we cannot see the folder, we cannot run the report. We confirmed the same in Chrome and Edge.

**Comment by GiantCrocodile** [comment]
I'm a bit disappointed by this feature: I found out that the generated .csv file contains no byte-order marker (BOM) and thus the file has to be imported in Excel via the import function. Otherwise the files and paths contain broken symbols like broken umlauts  in German language. This is annoying as an admin who just wanna double click the file or who wants to process this file in other systems. Adding this by hand or importing it with some clicks properly + saving it again every time is no solution. Service request #22088432 regarding getting someone to fix this issue by adding a BOM to the generated .csv file took nearly 2 months without achieving anything. Sorry but it's a disaster to see a company like Microsoft being not able to fix this issue nor being able to think about charsets/encoding from the beginning.

**Comment by StephenRiceMSFT** [comment]
@Jmartinez589, the report will cover the entire site collection. The folder selector is only for choosing where to save the report. If you are having issues with a location with large numbers of folders though, please do raise this issue via support so we can track. Thanks!

**Comment by StephenRiceMSFT** [comment]
@GiantCrocodile, thanks for submitting your feedback on this! This is definitely something we'll keep in mind as we look to improve the experience.

**Comment by scanum** [comment]
@Jmartinez589  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by Kasstriot** [comment]
You marked it as resolved, does this mean there is a PowerShell script available now?

**Comment by mrtsolutions** [comment]
Any update on running this report via powershell?
