### ISSUE TITLE
On the site, select Settings

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint#2563]
The page says:
Go to the More features page of the new SharePoint admin center, and sign in with an account that has admin permissions for your organization.

then 

Under Search, select Open.

On the search administration page, select Manage Search Schema.

Go to the Search Schema page for a site collection

On the site, select Settings Settings icon., and then select Site settings. If you don't see Site settings, select Site information, and then select View all site settings.

There is no "select Settings Settings icon." on the page!
You already have "Managed Properties|	Crawled Properties|	Categories" menu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b707d763-4c82-0d68-9cc7-35fb66935d25
* Version Independent ID: 4da67e73-1af9-ed9d-f367-4048ce5897fd
* Content: [Manage the search schema in SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/manage-search-schema#create-a-new-managed-property)
* Content Source: [SharePoint/SharePointOnline/manage-search-schema.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/manage-search-schema.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @Ofer-Gal How are you?

I think you had trouble following the instructions because there are two separated instructions:

_**Go to the Search Schema page for the tenant**_ instructions end in 3) and that is the page you get with the  "Managed Properties| Crawled Properties| Categories" menu that you mention.

and then, _**Go to the Search Schema page for a site collection**_ starts on the desired Site that you want to see the search schema page.

Kindly let me know if I understood you well.

**Comment by Ofer-Gal** [comment]
You are right! My bad.

**Comment by nam31** [comment]
@Ofer-Gal  Please let us know if you still have any question regarding the issue you have raised initially.
The issue is being closed since your question seems to be answered. Feel free to re-open this issue if you feel that it hasn't been answered or that there are further suggestions to improve the documentation itself.
Thanks.
