### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by ComputerHabit** [MicrosoftDocs/OfficeDocs-SharePoint#264]
There is no example of migrating individual SharePoint folders.  Further from the example I would gather I can only migrate entire sites and not portions of a site.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83229fe4-a0fc-5d45-1e32-2cf9bee9374b
* Version Independent ID: ea237f69-8d65-e3c6-1c77-5f3fdfb73d34
* Content: [Using PowerShell cmdlets to migrate to SharePoint Online](https://docs.microsoft.com/en-us/sharepointmigration/overview-spmt-ps-cmdlets)
* Content Source: [migration/overview-SPMT-PS-cmdlets.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/overview-SPMT-PS-cmdlets.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@ComputerHabit Thank you for this feedback

I will get this over to the SharePoint team for investigation and updating. 

I was able to get this into the backlog for the SharePoint team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by TokyoScarab** [comment]
Hello, thanks for sharing this feedback!  I would like to point out that the purpose of the doc for this issue is to point out and explain how to use the newly added PowerShell cmdlets that were based on the SharePoint Migration Tool Engine.  The examples on this page are showing off mass migration because the nature of the newer commands are more centered for that use.  For a list of all the PowerShell cmdlets that relate to SPMT, you can check out the full PowerShell reference complete with examples [here](https://docs.microsoft.com/en-us/powershell/spmt/intro?view=spmt-ps).  I hope this helps shed some light on your issue!

**Comment by scanum** [comment]
PR #705
