### ISSUE TITLE
Ther German site has some issues 

### ISSUE THREAD

**Issue by HansBrender** [MicrosoftDocs/OfficeDocs-SharePoint#2674]
good: https://docs.microsoft.com/en-us/onedrive/b2b-sync
with errors : https://docs.microsoft.com/de-de/onedrive/b2b-sync

Placeholders #A0 #A1

enclosed a picture, where Information are wrong!
![image](https://user-images.githubusercontent.com/57068122/113270277-975dd680-92d9-11eb-9668-2e1f3686953f.png)

**Comment by scanum** [comment]
@HansBrender Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@Officeglobal - Could you kindly help with this issue? Thanks!

**Comment by TinaMcN** [comment]
@HansBrender thank you for reporting this, it seems to be a very odd issue with the machine translation tool.  I can see that the issue is occurring in multiple German OneDrive articles.   I am following up with tool owners and hopefully they can fix it soon.  If not, I'll get these articles human translated.

**Comment by TinaMcN** [comment]
@HansBrender the machine translation tool are currently investigating this issue but it might take some time (weeks or months to fix it).  In the meantime I am sending some of the articles to be human translated.  FYI, I found over 3,000 German articles containing #A0, not just OneDrive articles.  I really appreciate you highlighting this issue.
