### ISSUE TITLE
Unable to upload viva connections app.

### ISSUE THREAD

**Issue by andreaslarssonliu** [MicrosoftDocs/OfficeDocs-SharePoint#2675]
Custom apps are enabled, just uploaded Qbot last week. 
The only error given is 
Manifest parsing has failed.
For more information, please visit aka.ms/teamsdocs

No errorcode

if i try to upload the app to a team I get the error
Manifest parsing has failed.
For more information, please visit aka.ms/teamsdocs

Errorcode "bad request"

Edutenant.
---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7210783d-e96e-9d14-9120-553f731d20ed
* Version Independent ID: 84854221-f26b-4a19-b95e-0d5d7c640a46
* Content: [Add Viva Connections for Microsoft Teams desktop - SharePoint in Microsoft 365](https://docs.microsoft.com/en-gb/SharePoint/viva-connections#step-by-step-guide-to-setting-up-viva-connections-desktop)
* Content Source: [SharePoint/SharePointOnline/viva-connections.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/viva-connections.md)
* Service: **sharepoint-online**
* GitHub Login: @Holland-ODSP
* Microsoft Alias: **hokavian**

**Comment by Holland-ODSP** [comment]
Hey @VesaJuvonen can you take a look at the comment above and let us know what you think? Any idea what might be going wrong?

**Comment by VesaJuvonen** [comment]
Hi @andreaslarssonliu - can you clarify a bit more on what exactly is the situation here.

If I read the exception correct, you have executed the PowerShell script which we provided and have received an exception as part of the solution upload to the Teams - is this correct?

If so - we can pretty much only speculate the root cause unless we have access on the manifest file. Any change you could share that with us - using personal messages works as well. Only way to understand what is wrong is to be able to view the content of the file.

Most likely there's some special character which breaks the solution. There's two simple things to check for additional details as well:

* If you create a new one with simple contoso values - does that work? - to validate your environment
* If you try to upload this solution to any other tenant - would that work? 

If you can't perform these, we are happy to help, but would need to get access on the zip file.

**Comment by andreaslarssonliu** [comment]
[Start.zip](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/files/6262623/Start.zip)

Might have been an issue with my icons, however a very confusing error message for such an error, however. 
My co worker managed to upload it, if your interested in checking out the file I've uploaded the zip file.

But as we managed to solve our issue i will close the error report.
