### ISSUE TITLE
Redirect information?

### ISSUE THREAD

**Issue by SeanGerlinger** [MicrosoftDocs/OfficeDocs-SharePoint#2772]
I think we need to mention the redirects that are created during the rename process. The redirect are not mentioned any where and maybe a warning to not delete them via PowerShell.

Sean Gerlinger

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Rename your SharePoint domain - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/tenant-rename)
* Content Source: [SharePoint/SharePointOnline/tenant-rename.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/tenant-rename.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@SeanGerlinger Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @SeanGerlinger, thank you for your feedback.

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=SeanGerlinger

I'm thinking in to add the following note to the article:
> [!NOTE]
> When you rename your SharePoint domain, we create a redirect at the previous address. If you want to reuse the previous address, you need to delete the redirect. [Learn how](manage-site-redirects.md)

What do you think?

If you can, could you kindly confirm the redirects that the rename process creates by running the following command?
Get-SPOSite -Template REDIRECTSITE#0

Thank you so much again!

**Comment by WayneEwington** [comment]
Redirect information has been added to the article. This can be closed.
