### ISSUE TITLE
Start-SPMTMigration reports Username or Password incorrect

### ISSUE THREAD

**Issue by Rupbret** [MicrosoftDocs/OfficeDocs-SharePoint#289]
I have tried using Global admin account, Azure user account, and AD synced account; all attempts to sync local SP2010 SharePoint Project server sub site with SharePoint Online returns error using provided script in this article. "Start-SPMTMigration : Username or password for target site https://.sharepoint.com/sites/testmig is not correct
 At line:27 char:1
•Start-SPMTMigration
•   + CategoryInfo          : InvalidArgument: (:) [Start-SPMTMigration], ArgumentException
  + FullyQualifiedErrorId : MigrationLibPowerShellError,Microsoft.SharePoint.MigrationTool.PowerShell.StartSPMTMigration"

**Comment by AndreaBarr** [comment]
@Rupbret Thank you for this feedback

I am not sure why this script is not working. Let me get this in front of the SharePoint team for investigation and updating. If you need the answer for this expedited please contact Support since they can also handle this inquiry. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by Rupbret** [comment]
Per Microsoft: The SharePoint Migration Tool lets you migrate lists or files from your SharePoint sever 2013 document libraries or from your on-premises file shares and move them to either SharePoint or OneDrive in Office 365. Migration from SharePoint 2007 is not supported.

**Comment by AndreaBarr** [comment]
@Rupbret Thank you for giving us this information.

I've added this to the backlog item so we can get this added to the article.

**Comment by AndreaBarr** [comment]
@tseward is investigating this issue.

**Comment by tseward** [comment]
@AndreaBarr this one can be closed. As stated, only SharePoint 2013 is supported so we expect SPMT to not function with SharePoint/Project Server 2010, 2016, and 2019.
