### ISSUE TITLE
Central documentation of OneDrive.exe Command Line Options

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftDocs/OfficeDocs-SharePoint#2905]
Hello, 

I have tried to find a listing of OneDrive.exe Command Line Arguments, but I cannot find anything. I tried opening a Microsoft Support case (Case #:1026127313) but they told me that OneDrive and they told me "unfoortunately [sic] there are no Command-line switches for OneDrive", even though there most definitely are. A couple examples of Command-line parameters [here](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise#install-onedrive-on-windows-devices-by-using-scripting-methods). 

It would be very helpful to update the Documentation for OneDrive to include some of these similar to this page - [Command Line switches for Microsoft Office Products](https://support.microsoft.com/en-us/office/command-line-switches-for-microsoft-office-products-079164cd-4ef5-4178-b235-441737deb3a6). For example: 

Through experimentation and scouring dozens of docs pages, hundreds of computer's activity, and random blogs, I have found this list of Command Line switches/parameters for OneDrive.exe, and there may even be several more, but I have not found them. 

```
/allUsers
/Background
/client= 
/configure_business
/configure_business:$tenantID
/firstSetup
/onPrem
/perMachineUpdate
/update
/RemoteBindToObjectWW
/remotedebug
/remoteport
/rz possibly
/silentConfig
/takeover
/url
/url:odopen://
/wait
/OneDrivePid:
/Shutdown
/Reset
```

These functions could be extremely useful for IT Admins when they are scripting. For example, `Onedrive.exe /Shutdown` is extremely useful - it shuts down OneDrive gracefully, and `onedrive.exe /background` starts it back up again without throwing up the File Explorer window. 
`OneDrive.exe /URL:odopen://$SharePointLibraryIDInfo` will start a SharePoint site Syncing through to File-Explorer - mostly silently. 
Or, another example, this could be used so that instead of making the user click several layers/pages deep on multiple sites to sync their libraries, the IT Admins could script it to sync the respective directories/sites. 

Currently, there is very little way to know what a given parameter like `/silentConfig` does though - Does it attempt to login with the settings from Group Policy? Does it Reset the current Profile's OneDrive and THEN try to login with the Registry Settings? Is it happy to just guess that you're logged in as johnsmith@contoso.one - so I'll see if I can SSO in with that? 

We _***need***_ actual documentation on these kinds of these Enterprise tools/features that are already in OneDrive and OneDrive.exe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9733a774-90dc-8726-3300-4660a092e427
* Version Independent ID: 3ab12184-9b19-1686-e9d9-a96a93e3fea4
* Content: [OneDrive guide for enterprises - OneDrive](https://docs.microsoft.com/en-us/onedrive/plan-onedrive-enterprise)
* Content Source: [OneDrive/plan-onedrive-enterprise.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/plan-onedrive-enterprise.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by adeejoseph** [comment]
@PsychoData  I'm the new owner of this content.  Thanks so much for bringing this to our attention. I absolutely agree that this information would be extremely helpful to Admins. I will get started on creating documentation accordingly. Your feedback is greatly appreciated!

**Comment by Slaymeister** [comment]
I've been looking all over for this, and I've seen many threads of people asking the same question. I'm glad the documentation is going to be produced.  In the meantime, is there a switch for pause and resume sync without shutting down onedrive, or are the switches only for starting a new instance?

**Comment by HansBrender** [comment]
Hey @Slaymeister , you shoud first read the [Limits and restrictions](https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa)  (here 300.000) files. So you will get into trouble
Second: Reset is do, what it should, Also [here ](https://support.microsoft.com/en-us/office/reset-onedrive-34701e00-bf7b-42db-b960-84905399050c)an Article for you.

**Comment by mtaylor-dev** [comment]
Thank you for this! It was a huge help just the other day. We're just starting to roll out the client and someone thought it'd be a good idea to change our Azure tenant name without researching the potential impact. We use Azure AD SSO w/ Hybrid Joined workstations and domain group policies for configuration so our OneDrive client automatically signs in the Windows user. Some notes that may help others. Using this code running under logged on user context (with some other company specific code) I was able to update my pilot user's OneDrive folders to the new name. Silently re-logged in the user with the new path and Known Folder Move even re-applied.
```PowerShell
Get-Process onedrive | Stop-Process -Force
Start-Sleep 5

$regPath = Join-Path -Path 'HKCU:\Software\Microsoft\OneDrive\Accounts' -ChildPath 'Business*' -Resolve
if($regPath){
    Remove-Item -Path "$regPath" -Recurse -Force
}

Set-ItemProperty -Path "HKCU:\Software\Microsoft\OneDrive" -Name 'ClientEverSignedIn' -Value 0 -Force | Out-Null
Set-ItemProperty -Path "HKCU:\Software\Microsoft\OneDrive" -Name 'SilentBusinessConfigCompleted' -Value 0 -Force | Out-Null
Start-Process 'C:\Program Files\Microsoft OneDrive\OneDrive.exe' -ArgumentList '/silentConfig /configure_business:<Your TenantID>'
```

**Comment by Merlin2001** [comment]
@PsychoData: Wow, I just missed `/shutdown` there because while it was in the text but not in the list formatted as code. So I just assumed it had been removed 😅 . If you feel like editing your post, it would be amazing to have it in the list explicitly, too 🤓 

Thank you for compiling this!

**Comment by PsychoData** [comment]
/odopen I knew about, it's how the odopen:// protocol works, which is how SharePoint syncs folders to your local explorer through OneDrive

How did I miss adding /shutdown?? That's the one that I found and started this whole thing with! I'll add that thanks

**Comment by PsychoData** [comment]
/odopen I knew about, it's how the odopen:// protocol works, which is how SharePoint syncs folders to your local explorer through OneDrive

How did I miss adding /shutdown?? That's the one that I found and started this whole thing with! I'll add that thanks

**Comment by PsychoData** [comment]
I made a OneDrive module in PowerShell that does some things with a couple of the parameters, and edit the local config file to remove synced libraries
https://www.powershellgallery.com/packages/Onedrive-client

**Comment by PsychoData** [comment]
Is there any movement with this? 
Still no idea how many of these switches work, if there are new ones, if any are removed, et cetera

**Comment by robinmalik** [comment]
It seems as though the `/Background` switch isn't behaving as expected. When users logon to our Azure Virtual Desktop infrastructure they're getting the explorer window popup. 
Running OneDrive Build 22.121.0605.0002.

**Comment by jjwb96** [comment]
Has there been any movement on this?

**Comment by jirikm** [comment]
Hi, any news please?

**Comment by tiburd** [comment]
Thank you, everyone, for sharing this information. The documentation team has OneDrive command-line options on their list of items to document. Unfortunately, there is not an ETA for when that documentation will be published.

**Comment by Merlin2001** [comment]
@tiburd Could you please keep this issue open as long as it's not actually done?
I fear that otherwise it could get lost and never be actually improved :/

**Comment by tiburd** [comment]
> @tiburd Could you please keep this issue open as long as it's not done? I fear that otherwise it could get lost and never be improved :/

I understand that perspective/request. However, because our team has confirmed that the documentation team is tracking the issue in their workflow, our process is to close the issue.

**Comment by cmakas** [comment]
On my test client (Win11, current updates) I tried today /Shutdown and it worked 3 times and then it did not work anymore.
(When) Did it get deprecated?

**Comment by tiburd** [comment]
> On my test client (Win11, current updates) I tried today /Shutdown and it worked 3 times and then it did not work anymore.
> (When) Did it get deprecated?

@cmakas 
I have reached out to the team to try to get that information for you. I'll add another comment when I receive a response.
Thanks!

**Comment by gaiking-uk** [comment]
# Short version
Wow, I can't believe I've only just learnt about the the /shutdown and /background options today 🤦🏼‍♂️ -- For ***years*** I've been running ```taskkill /IM onedrive.exe /F``` to help support/administer OneDrive (including in scripts that have been deployed, etc) as I didn't know it had it's own built-in shutdown command(!)

This documentation is ***long*** overdue (and it's even more disappointing to then find out that despite @PsychoData putting in the work himself, compiling the command line options and just asking Microsoft to fill-in the blanks and publish it, after 18 months Microsoft still haven't done anything on this ☹️

**Comment by gaiking-uk** [comment]
# Long version

@tiburd - I see there's been no update for over a month, presumably the team hasn't gotten back to you on this(?)

### Please Escalate

If you are unable/unwilling to re-open the ticket here [I understand there is a process to follow], please can I ask you to **escalate this internally** with the documentation team. As while the issue of "an OneDrive end-user / IT admin help page not being published" may be relatively minor say compared to something like a P1/multi-tenant outage, it is something that is is likely having a detrimental impact to Microsoft's reputation and regard in the community...

### Issue Summary
- **CORE ISSUE: NO ONEDRIVE DOCUMENTATION** -- Microsoft never published any comprehensive information on the command line options available for OneDrive. This made it more difficult for the **thousands+** of IT admins to support across millions of end-users
- **USER FRUSTRATION EVIDENT** -- Tired of the complete lack of documentation, @PsychoData spend hours of his own time, scouring the internet and reading dozens of articles/pages to try and understand what command line options are accepted by OneDrive.exe
- **PROBLEM CONFIRMED** -- Multiple users confirmed that the lack of documentation had been a point of frustration and/or made administration and user support more difficult. Microsoft themselves agreed this documentation was lacking and would definitely be of benefit to publish
- **MICROSOFT WORK MINIMISED** -- To simplify the task and reduce the amount of work/time needed, @PsychoData started the documentation task for Microsoft by compiling the information into a single list and asked Microsoft to check it, complete it and publish it so users had access to this information
- **NO ACTION** -- More than 18 months after Microsoft were given the information to publish, it has still not been made available. Users have repeatedly asked for updates on this but there seems to have been no meaningful progress since 2021

### Microsoft Reputation Impact
- **SLOW** -- The fact that the "starter page" was given to Microsoft but the documentation team hasn't got around to completing/publishing it after 18 months shows Microsoft to be ***extremely slow*** in addressing issues and providing useful information to the community
- **INEFFECIENT** -- When comparing the amount of time needed (est. 2 hours) with the amount of time Microsoft have had to action this (multiple years) and still counting! shows Microsoft to seemingly be incapable of getting even small/simple tasks done in any kind of reasonable timeframe
- **UN-CARING** -- The fact that the community went 'above and beyond' and spent hours of personal time to compile this information ***for Microsoft***, while Microsoft seemingly have not done anything with it, re-opened the ticket or escalated the issue shows Microsoft to be somewhat un-caring to the community
- **COMMUNITY DISENGAGEMENT** -- 
  - This issue [small documentation request] was first raised to Microsoft in 2021...
  - It being acknowledged and appreciated by Microsoft at the time...
  - But 2 years later in 2023, there seems to be no meaningful progress / action by Microsoft...
  - Multiple users asked repeatedly for updates on this and/or the ticket to be re-opened, however the issue remains "closed" despite nothing being done and the problem still existing...
  - While I can't speak for @PsychoData (or anyone else) if it was me that I had spent time researching this and raising it to Microsoft, only to see nothing happen for several years -- I have to say it would make me seriously question whether I would bother giving feedback or raising requests to Microsoft again in the future, as it seems to be somewhat pointless

***

[**TONE CLARIFICATION**] While my disappointment on this issue is no-doubt evident and I've outlined how ***Microsoft*** could be accused of being slow, inefficient, etc on this, it is not my intention to insult/offend ***anyone personally***... At the end of the day, I realise that we are all just people trying to do the best we can and there are often constraints outside our control. I would just implore you once again @tiburd (or anyone else managing this) to please do what you can at your side to nudge this along and get it resolved, as hopefully you also agree that 18 months to write a page on OneDrive.exe options is a bit much and we just need to get this done.

**Comment by tiburd** [comment]
@cmakas 
I sincerely apologize for the delay in getting back to you. Here is the reply we received to your March 2 question:
> There’s no new info on this. We appreciate the feedback but there’s nothing in the schedule for documenting this right now.
> 
> If someone’s having trouble with commands not working as expected, they should open a support ticket.


@gaiking-uk 
Thank you for taking the time to submit thorough feedback. I am seeking the appropriate person/team to receive it.

**Comment by tiburd** [comment]
@gaiking-uk 
We have contacted the product team and asked whether we can expect onedrive.exe command line switches documentation in the foreseeable future. I'll update you when we hear back.

Thank you.

**Comment by cmakas** [comment]
> 

Thanks, that would be great!

**Comment by gaiking-uk** [comment]
Hi @tiburd, thanks for the update!

Hopefully this can be accepted into the pipeline and be published soon... If you do get any push back, please do stress to the team that:
1. It is in the ***public interest*** to publish this information, and more specifically it helps OneDrive MVPs and IT Pros helps support end users and organisations
2. The information is ***already public*** (so shouldn't be any privacy concerns) however the issue is that the information is not easy to find, as it's attached to [documentation issue 2905](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2905) or scattered around the internet with different articles/pages advising on different switches that can be used -- rather than being consolidated on a dedicated Microsoft *learn* or *support* page
3. ***An initial draft has been provided***, and the ask is primarily just to ***verify and publish*** this information - so hopefully this should be much quicker for the team (as apposed to asking them to research this info and write the page(s) from scratch)

Thanks for continuing to push this forward 👍🏼

**Comment by HansBrender** [comment]
but many issues are not  from the sync engine.  there are so many errors, which has nothing to do with  the sync engine. 
Admins should know about tehese [restrictions and limitations](https://support.microsoft.com/en-us/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa)

**Comment by Merlin2001** [comment]
@HansBrender : I'm not sure I understand your comment. It seems unrelated to the topic of this thread (in short: adding the available command line options of `onedrive.exe` to the public facing documentation).

Can you clarify what message you are referring to?

**Comment by HansBrender** [comment]
If there is an error, you cannot change that with an command on the OneDrive.exe

**Comment by gaiking-uk** [comment]
Hi @HansBrender, thanks for your message and the link 👍🏼 

**Side note**: I would particularly encourage everyone to be conscious of the [100,000 max synced files recommendation](https://support.microsoft.com/en-gb/office/restrictions-and-limitations-in-onedrive-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#synctoomany)
- Over the years I had crept up and over this limit without issue, until recently when OneDrive stopped syncing
- `OneDrive.exe /reset` did not fix the sync
- In the process it actually corrupted / reverted ~1000 files!
- I re-imaged the machine, but synced stopped working again after a week
- Ultimately, the only fix was to re-structure my OneDrive and move out 40,000+ files to get back under the 100,000 limit
- Since then it has been fine, however I would not want anyone else to have to go through the ordeal of fixing ~1000 duplicated and/or reverted documents like I had to!

***

> If there is an error, you cannot change that with an command on the OneDrive.exe

Just to check we're on the same page, this request isn't about changing or adding any functionality in OneDrive, it is simply about getting the documentation published so that admins and support teams can write better scripts, make better `OneDrive.exe` calls, are able to use OneDrive *more powerfully* and support users better.

Consider:
```
:: Restart-OneDrive-Basic.bat
:: -----------------------

TASKKILL IM OneDrive.exe /F
OneDrive.exe
REM OneDrive opens a new explorer window, tell user to close/ignore it
```
vs. 
```
:: Restart-OneDrive-WithSwitches.bat
:: -----------------------

OneDrive.exe /Shutdown
OneDrive.exe /Background
REM Lets OneDrive deal with any active uploads/downloads, exit gracefully and restart in the background
```
Hopefully everyone would agree `Restart-OneDrive-WithSwitches.bat` is a much better approach, however the core of the issue is that these additional switches are not well (or in some cases, even at all) documented so the wider community is not able to take advantage of them.
... Imagine `ROBOCOPY` with no manual / help page!

Hope that helps clarify the goal.

***

@tiburd -- Hi Tina, hope you are well!
- Just wanted to check if there has been any update on this internally yet please?
- Also, for better tracking and transparency if this documentation request is in essence accepted(?), can we re-open the ticket please and thus help to track it as an active work item?

Thanks,
Martin

**Comment by tiburd** [comment]
Hello,

I reached out again yesterday, but I haven't heard back yet.... Unfortunately, I don't think re-opening the issue would help expedite results. 

In the meantime, you might want to provide feedback via the [OneDrive Feedback Forum](https://feedbackportal.microsoft.com/feedback/forum/e3f04660-2c1c-ec11-b6e7-0022481f8472).

**Comment by Merlin2001** [comment]
Thank you for pointing to the feedback forum, @tiburd!

I created basically a copy of this issue that you can find here to cast your vote(s): [Add central documentation of OneDrive.exe Command Line Options](https://feedbackportal.microsoft.com/feedback/idea/b525fa87-a9f0-ed11-a81c-0022484f9f6d)

(@PsychoData: I hope this is ok for you, if not, please let me know and I'll delete the issue!)

**Comment by JVKeller** [comment]
Any updates? It would be great to be able to silent install onedrive with switches to be able to sign in the user during process.

**Comment by gaiking-uk** [comment]
> Any updates? It would be great to be able to silent install onedrive with switches to be able to sign in the user during process.

@JVKeller -- Unfortunately, I am checking out of this issue now... I have been trying to nudge this along for several months, posting multiple messages and spending hours of my own time, adding 1,300+ words to the topic, but AFAICT literally nothing has happened 😔

I literally, explicitly warned Microsoft months ago about [the risk of community disengagement](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2905#issuecomment-1499725632) if nothing happened, yet here we are...

## Request: Add 1 page to the Microsoft docs website

## Response: Microsoft's implementation / process...
- Time required: ***MULTIPLE YEARS***
- People required: ***OVER 1 DOZEN, posting 30+ messages***
- Effort required: ***EXCESSIVE***

***

@tiburd -- You hopefully remember from my previous messages that this is not a personal against anyone involved but I literally just don't have the words... I mean, it literally boggles my mind how it can possibly be this difficult to ***ADD 1 PAGE TO A WEBSITE!*** 🤦🏼‍♂️

***

## My Conclusion
- There has been no progress or action on this in the ***YEARS*** since it was posted and requested
- If it hasn't happened by now, realistically ***I DOUBT THIS WILL EVERY HAPPEN***
- This could and should have been a "quick win" for Microsoft and the community... "Microsoft, I have compiled a list of useful but currently un-documented parameters for OneDrive -- Ah, amazing, thank you, we'll publish that as official documentation on our website" -- Result:  Microsoft 👍🏼 Community 👍🏼
- Instead it has seemingly been a complete farse and waste of time for everyone involved.... I mean more time and effort has gone into this page than the original documentation itself!
- Not angry or bitter, just disappointed beyond words
- Please Microsoft, prove me wrong, make this right!

**Comment by PsychoData** [comment]
> I reached out again yesterday, but I haven't heard back yet.... Unfortunately, I don't think re-opening the issue would help expedite results.
> 
> In the meantime, you might want to provide feedback via the [OneDrive Feedback Forum](https://feedbackportal.microsoft.com/feedback/forum/e3f04660-2c1c-ec11-b6e7-0022481f8472).

Hi @tiburd, just checking back in on this again. Reading through the others trying to follow up with this re-inspired me to check on this again. 

Gaiking hit the nail on the head with [the risk of community disengagement](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2905#issuecomment-1499725632) - I gave up on this issue a long time ago, although I still was struggling to find OneDrive switches just yesterday (and ended up re-discovering my own years-old request for help!) 
Kind of exciting that my issue requesting documentation seems to show up on the first page of search engine results for every separate one of the commands! Shame that there is literally no movement on this more than two year old issue. 

You suggest opening a Support Ticket if any of the switches are not working, but I did just that before I ever opened this issue in GitHub! OneDrive for Business support told me that the switches I was using didn't exist. When I pressed on with them, trying to get them to give me an idea how it worked, they just suggested I open this issue! Hence why as soon as the talk turned back to "go open a support ticket!" I gave up on this entirely, because it was just back to the Meme of Microsoft's Org Chart blaming each of the other divisions

And now it is saddening to see Microsoft "[Unveiling the Next Generation of OneDrive](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/unveiling-the-next-generation-of-onedrive/ba-p/3935612)" when they haven't even fixed/documented the current version! 

I would love nothing more than to be proven wrong, but I don't think the Documentation Team cares enough to actually fix the issue, or I am better they don't even care enough to follow up with you and let you know the last time that someone there worked on this. I know that it is frustrating checking in with the other team for them to just say that they still have done nothing with this, but every time one of you on these teams check on this or tries to escalate it to get the Documentation Team do what they already should have done probably back on 2007 when it was SkyDrive, or sometime after 2014 when it became OneDrive, there is a slight chance that things will improve. 

I will finish this round of the post saying Gaiking said he wasn't bitter / angry, just dissappointed - but I am bitter. "[angry, hurt, or resentful because of one's bad experiences](https://www.bing.com/search?q=bitter#:~:text=angry%2C%20hurt%2C%20or%20resentful%20because%20of%20one%27s%20bad%20experiences)" and not for the first time.

**Comment by magoerlich** [comment]
> _**Microsoft**_ could be accused of being slow, inefficient, etc on this

6 month later without **any** further progress one could argue these accusations were correct, because this issue and the way it's handled makes it obvious, that they either don't care or actually ARE slow and inefficient.
Maybe even both...

**Comment by TeamDman** [comment]
I just want to programmatically ensure that a file is available on my device. There's APIs and stuff for onedrive but downloading a file isn't the same as having the file that's 'already on disk' but remote-only be pulled down.

`File -> Open -> hello.txt (status: online only)` will make OneDrive download the file just-in-time/on demand.

However, doing `notepad.exe "C:\Users\TeamD\OneDrive\Documents\onedrivetesting\hello.txt"` results in an error

> You do not have permission to open this file. See the owner of the file or an administrator to obtain permission.

So, perhaps the file picker is what invokes the JIT download?

# "Always keep on this device" context menu option

Maybe this action can be done programmatically?

Ctrl+F'ing the registry for "Always keep on this device" finds

```reg
"@windows.fileexplorer.common.dll,-51331"="Always keep on this device"
```

Ctrl+F'ing for "-51331" finds

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AllSyncRootObjects\shell\MakeAvailableOffline]
"CommandStateHandler"="{51CAFEF2-C040-4022-A152-53033EE9A02B}"
"CommandStateSync"=""
"Description"="@windows.fileexplorer.common.dll,-51332"
"MUIVerb"="@windows.fileexplorer.common.dll,-51331"
"NeverDefault"=""
"SkipCloudDownload"=dword:00000000
"StorageProviderFlagsRequired"=dword:00000002

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\AllSyncRootObjects\shell\MakeAvailableOffline\Command]
"DelegateExecute"="{51CAFEF2-C040-4022-A152-53033EE9A02B}"
```

The `DelegateExecute` is a CLSID apparently, which is a COM thing?

```reg
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\CLSID\{51CAFEF2-C040-4022-A152-53033EE9A02B}]
@="Sync root make available offline verb"

[HKEY_CLASSES_ROOT\CLSID\{51CAFEF2-C040-4022-A152-53033EE9A02B}\InProcServer32]
@="C:\\Windows\\System32\\Windows.FileExplorer.Common.dll"
"ThreadingModel"="Apartment"

[HKEY_CLASSES_ROOT\CLSID\{51CAFEF2-C040-4022-A152-53033EE9A02B}\SupportedProtocols]
@="*"
```

so it looks like `Windows.FileExplorer.Common.dll` has the functionality we desire.

# GitHub

A [search](https://github.com/search?q=Windows.FileExplorer.Common.dll&type=code) reveals 330 usages of `Windows.FileExplorer.Common.dll`.

It seems a lot of people put registry dumps and stuff on GitHub, so there's a lot of noise if you ever try and search for COM objects and stuff, but in this case there's [a file](https://github.com/strontic/strontic.github.io/blob/c7fd71fd347a239cb0edb50c73704de59b410c32/xcyclopedia/library/Windows.FileExplorer.Common.dll-F475A3C22F664C335280A6486C1CE894.md?plain=1#L25) with a list of DLL exports:

Function Name | Ordinal | Type
-- | -- | --
`FECommon_PerformCloudFilePinAction` | 2017 | Exported Function
`FECommon_SetPlaceholderReparsePointAttribute` | 2018 | Exported Function
`FECommon_GetStorageProviderDisplayName` | 2015 | Exported Function
`FECommon_GetStorageProviderInfoFromItem` | 2016 | Exported Function
`FECommon_SetPlaceholderReparsePointAttribute2` | 2019 | Exported Function
`RegisterChangeNotifications` | 2004 | Exported Function
`UnregisterChangeNotifications` | 2005 | Exported Function
`FECommon_UpdateFilePlaceholderStates` | 2020 | Exported Function
`GatherProviderSettings` | 2003 | Exported Function
`FECommon_GetSkyDriveNetworkStates` | 2014 | Exported Function
`DllGetClassObject` | 2007 | Exported Function
`FECommon_BindToFilePlaceholderHandler` | 2008 | Exported Function
`ApplyProviderSettings` | 2002 | Exported Function
`DllCanUnloadNow` | 2006 | Exported Function
`FECommon_CreatePlaceholderFile` | 2010 | Exported Function
`FECommon_FilePlaceholder_CreateInstance` | 2012 | Exported Function
`FECommon_GetPlaceholderStatesFromFileAttributesAndReparsePointTag` | 2013 | Exported Function
`FECommon_CSyncRootManager_CreateInstance` | 2009 | Exported Function
`FECommon_FilePlaceholder_BindToPrimaryStream` | 2011 | Exported Function

Other than this, I can't find any other useful references to `Windows.FileExplorer.Common.dll` on GitHub.

Googling/Bing'ing "51CAFEF2-C040-4022-A152-53033EE9A02B" didn't yield anything new either.

Thinking more about it, it's probably thanks to all these people putting this stuff on github that you can paste a CLSID into ChatGPT and it might know what you're talking about lol.

# Finding parameters for the CLSID

"C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x64\oleview.exe" is neat but doesn't seem to have what I want.

# idk

This is about as far as I got. I can only guess that I just want to call "FECommon_PerformCloudFilePinAction", but I'm a bit out of my depth at this point for how to proceed.

What I'd love is for OneDrive.exe to have a `--help` / `/?` printout instead of opening my onedrive folder in explorer.exe

What I'd love even more is if there was a way to use onedrive.exe to 
- accept a list of file paths and will make sure they are available on the device

I'd also imagine this would be useful:
- accept a list of file paths and return the mapping to whatever each path's onedrive identifier is
- accept a list of onedrive identifiers and return a mapping for file paths



I'm not sure why this is buried, I would think that helping developers build programs that entrench onedrive-based workflows would be good for business?

**Comment by PsychoData** [comment]
You can also use attrib.exe to set "always keep on this device"

https://learn.microsoft.com/en-us/sharepoint/files-on-demand-windows

**Comment by seanvandermolen** [comment]
![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/7504775/205fc3ac-9690-4e61-ad6a-4a064efd7985)
