### ISSUE TITLE
Command does not exist

### ISSUE THREAD

**Issue by cwdata** [MicrosoftDocs/OfficeDocs-SharePoint#2930]
@SaladiHarini 
I removed the SharePoint Online Management Shell from my computer and installed the current version from the link on this page (16.0.21610.12000)
I was then able to follow the provided steps until this command should be used:
Add-SPOListDesign
Powershell throws an error that this CmdLet does not exist. Digging through the available CmdLets I couldn't find anything that looks like that.
Where could we download a SPO Management Shell that contains this CmdLet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6665386e-1ad4-e9d3-565b-4b3cb3c3ea99
* Version Independent ID: 870237f7-66ec-270e-1372-c993e8dedbe9
* Content: [Custom list templates - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/lists-custom-template)
* Content Source: [SharePoint/SharePointOnline/lists-custom-template.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/lists-custom-template.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by SaladiHarini** [comment]
@cwdata: Add-SPOListDesign is a new Lists specific cmdlet that should be available to you are running this against a tenant that is in TR. [We are in the process of rolling out to PROD over the next few weeks]. We are also working on updating the documentation [here](https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/?view=sharepoint-ps) to include details of the cmdlet.

**Comment by cwdata** [comment]
@SaladiHarini
thanks for the quick response. Yes, the tenant I'm connecting to is set to Targeted Release for everyone.
And I agree with you that the cmdlet Add-SPOListDesign 'should' be available, but unfortunately it is not.
Entering the command
Get-Command *ListDesign*
in Powershell yields no results. Hence that cmdlet is missing in the currently available SharePoint Online Management Shell.
So I'm wondering if there is a beta version or something like that of the Management Shell which we could download and which contains the command. We would like to try out this functionality.

**Comment by SaladiHarini** [comment]
Hey @cwdata! I've tested with a TR tenant and I do see all the list related cmdlets available in the version of Microsoft.Online.SharePoint.PowerShell that I'm running (16.0.21513.12000). Let's try to troubleshoot this! Thanks for your patience :)

Here are some steps I recommend: 

- Run PS as administrator. Use the following command to check your version of Microsoft.Online.SharePoint.PowerShell
`Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version`
- If it doesn't match the version I'm on (which is the latest), please uninstall and let's try to reinstall via Install-Module
- Here is how you can install and update from PS instead of trying to get the latest version by downloading every single time:
`Install-Module -Name Microsoft.Online.SharePoint.PowerShell`
- You can then run the following command to make sure you are always running the latest bits!
`Update-Module -Name Microsoft.Online.SharePoint.PowerShell`

I'm hoping at the end of this you'll be able to run through all the steps in the article, but if not, please reach out and we can connect on a call to troubleshoot live!

**Comment by scanum** [comment]
Thank you for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by cwdata** [comment]
@SaladiHarini,
thanks to your help I found out that even though I uninstalled the old version of the SPO Management Shell another old version was still loaded from somewhere else. After removing that one with Uninstall-Module the command Add-SPOListDesign is now available to me.
Another quick question: Is it planned to have this kind of templates also for document libraries?

@scanum,
the availability of commands in a PowerShell session is in no way related to the tenant. It's a matter of what the installed modules on the local system have built in. It might be a good idea to add a paragraph on how to identify and fully uninstall all old versions of the SPO Management Shell, which would be:
`Get-Module -Name Microsoft.Online.SharePoint.PowerShell -ListAvailable | Select Name,Version`
and if any were found:
`Uninstall-Module -Name Microsoft.Online.SharePoint.PowerShell -AllVersions`
This might need to be done in addition to uninstalling the Shell from 'Installed Apps'.
