### ISSUE TITLE
LInk Broken

### ISSUE THREAD

**Issue by rajeshswim** [MicrosoftDocs/OfficeDocs-SharePoint#295]
The   SharePoint site design and site script overview link in Step 7, is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4df1d8-955c-63d2-628e-8359391b8710
* Version Independent ID: 01326ab6-1270-d096-64e8-eb7d63ea9863
* Content: [Create a hub site in SharePoint Online](https://docs.microsoft.com/en-us/sharepoint/create-hub-site)
* Content Source: [SharePoint/SharePointOnline/create-hub-site.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/create-hub-site.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@rajeshswim Thank you for this feedback

I will get this link looked at and have it updated so that it works. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by kaarins** [comment]
@rajeshswim, this is fixed now. Thanks for pointing it out!
