### ISSUE TITLE
unable to find settings being referenced

### ISSUE THREAD

**Issue by bernardw1** [MicrosoftDocs/OfficeDocs-SharePoint#297]
I am trying to find the popularity and search reports refered to in this article but I am unable to find them.

when I go to Site Settings &gt; Site Administration &gt; I do not see a Popularity Trends.
Same as when I go to Site Settings &gt; Site Collection Administration &gt; I do not see a Popularity and Search Trends.

This is in Sharepoint online/O365.
![image](https://user-images.githubusercontent.com/23319226/46483776-0cf69380-c7be-11e8-8383-365d05ff7103.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb55f79c-8118-474e-175b-f8cfb0737bc4
* Version Independent ID: 43071ae4-5da9-056b-9bd9-333fb100c8ef
* Content: [View Popularity Trends and Most Popular Items](https://docs.microsoft.com/en-us/sharepoint/view-popularity-trends-and-most-popular-items)
* Content Source: [SharePoint/SharePointOnline/view-popularity-trends-and-most-popular-items.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-popularity-trends-and-most-popular-items.md)
* Service: **sharepoint-online**
* GitHub Login: @tklarsen
* Microsoft Alias: **tlarsen**

**Comment by AndreaBarr** [comment]
@bernardw1 Thank you for this feed back

It's odd that Popularity Trends is not listed for you. I want to get this over to the SharePoint team for investigation. I also want to get you over to Support as well so that we can tackle this on both ends. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by bernardw1** [comment]
Thank you for the response. I will open a case with support tomorrow when I have some time to dig into the issue. (I am guessing at least that you wanted me to open the case with Support).

**Comment by AndreaBarr** [comment]
@bernardw1 yes please open a case with Support when you can.

**Comment by tseward** [comment]
This looks like a Modern Team site. You should instead be using the Site Usage. You can find this in the Gear icon -> Site Usage.
