### ISSUE TITLE
Finally tenant rename working 

### ISSUE THREAD

**Issue by eduardo-publi** [MicrosoftDocs/OfficeDocs-SharePoint#3061]
[Enter feedback here]
As of today (24/Nov/2021) we can do our tenant rename option.
Step 2 can also be made directly on the azure portal, without powershell or modules.
Just use magic aka link
https://aka.ms/SPORenameAddDomain
As it put 
&Microsoft_AAD_IAM_tenantRenameAllowed=true 
at end of URL.
Besides of creation of another desiredtenant.onmicrosoft.com, you can also set the initial domain directly from the portal
![image](https://user-images.githubusercontent.com/94030458/143247052-c3d0e91f-0e5d-408b-b28e-8d5602a1cf4c.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2454cb9a-dfa4-9c8a-3671-3150d49f74c7
* Version Independent ID: e0a4a71a-aa4d-1066-8f76-742c3411f06c
* Content: [Change your SharePoint domain name - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name)
* Content Source: [SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/change-your-sharepoint-domain-name.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by eduardo-publi** [comment]
And my tenant wasn't signed the form for this public-preview as noted at end of this post
https://strive2code.com/post/2021/09/15/o365-tenant-rename

**Comment by get-itips** [comment]
Hello @eduardo-publi 
How are you? Is there anything you see in the article that you think needs a correction?
Thank you!

**Comment by eduardo-publi** [comment]
Hello @get-itips, 
I just guess this article should be moved to a higher level, as it not only affects only Sharepoint, but entire Office 365 services.

**Comment by get-itips** [comment]
Hello, Eduardo @eduardo-publi thanks for clarifying.
If I understand correctly, did you follow this guide step by step and that also changed your tenant name for other services? Please correct me.
Thank you!

**Comment by Arthur-Avanesyan** [comment]
Clicking "Configure initial domain" gives "No access" error.

![image](https://user-images.githubusercontent.com/65603239/147408987-926c8bb3-6bf3-4552-8572-84a1777c2aa9.png)

**Comment by MadDog2K** [comment]
> Clicking "Configure initial domain" gives "No access" error.

I experience the exact same issue, haven't found a solution yet

**Comment by VerisZG** [comment]
> Clicking "Configure initial domain" gives "No access" error.
> 
> ![image](https://user-images.githubusercontent.com/65603239/147408987-926c8bb3-6bf3-4552-8572-84a1777c2aa9.png)

Same.

**Comment by mubbery** [comment]
Success but not quite the way described above. I managed to delete the original xxx.onmicrosoft.com domain by doing the following.

1. Navigate to Admin Centre > Domains
2. Click the onmicrosoft.com domain you want to change / replace
3. Click the "Add onmicrosoft.com domain" link (See pic) and create a new onmicrosoft.com address to use as your tenant name.

![image](https://user-images.githubusercontent.com/986918/150705813-9ebbf2b7-9974-42b4-a99d-a3f7a4854afc.png)

4. Navigate back to the Domains section.
5. Click on the original onmicrosoft.com domain again.
6. Click the "Make Fallback" button.
7. Navigate back to the Domains list and you should now be able to remove the original onmicrosoft.com domain.

Some notes:
I had to F5 the page a few times to, and the removing of the original domain took some effort due to dependencies but once I did that it all seems to work fine.
Also the domain is labelled "Available" rather than verified in the AAD portal. I'm investigating this now,

Lets hope I didn't just bork my tenant, though everything seems fine so far. Emails are working for my custom domain so that is the main thing :)

**Comment by Speed25** [comment]
Hello,
Has anyone tested renaming with Sharepoint, Dynamics and Teams ?

**Comment by Developix** [comment]
Clicking "Configure initial domain" gives "No access" error here as well.
Error 403 = "Access Denied"

**Comment by prtkdv** [comment]
> 

Yes, I have done it, you have to set time in future date. https://docs.microsoft.com/en-us/sharepoint/change-your-sharepoint-domain-name

**Comment by mlomat** [comment]
I was able to create new custom domain and migrate users and everything looks good, but I cannot remove custom domain. Even I created additional domain for test, with no reference to anything, and I cannot remove it. Any idea how to fix it? 
![image](https://user-images.githubusercontent.com/7577121/162747915-7d4f1476-d961-4323-a03e-82227903b1df.png)

**Comment by valentinocossar** [comment]
Same error as @mlomat for me, any suggestion?

**Comment by diamondelf** [comment]
FYI, you cannot remove .onmicrosoft.com domain, and you are limited to five onmicrosoft.com domains in your Microsoft 365 environment. see below article
https://docs.microsoft.com/en-us/microsoft-365/admin/setup/domains-faq?view=o365-worldwide#why-do-i-have-an--onmicrosoft-com--domain
