### ISSUE TITLE
Description does not match what is available in reality.

### ISSUE THREAD

**Issue by DaKarli** [MicrosoftDocs/OfficeDocs-SharePoint#309]
Hi kaarins,

something must be wrong because if I follow this description, there is no menu or link as described in paragraph 5.

I hope you can verify and correct this. Or did I find a future feature? ;-)

Cheers, Harry.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0293eda0-8476-a578-fe89-8320208e03bc
* Version Independent ID: 8077916b-34d4-4bfa-a77f-e577249f99ab
* Content: [Ändern Sie die externe Freigabe Einstellung für einen Benutzer OneDrive](https://docs.microsoft.com/de-de/onedrive/user-external-sharing-settings)
* Content Source: [OneDrive/user-external-sharing-settings.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/user-external-sharing-settings.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by AndreaBarr** [comment]
@DaKarli Thank you for this feedback

It sounds like you might have stumbled on a potential bug. So that we can get this documented and addressed promptly I would like to have you open a Support case. Support can document this and has more resources to handle potential bugs. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
