### ISSUE TITLE
Does this setting only create Conditional Access Policies?

### ISSUE THREAD

**Issue by AlexSchwerzmann** [MicrosoftDocs/OfficeDocs-SharePoint#3114]
Hi Microsoft

It's still not clear in the article if the setting does only create an according Conditional Access policy (better said two of them) or if it does more. Specially the hint that we can create advanced limits (https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices#advanced-configurations) doesn't sound like a Conditional Access Policy-only thing. Could you precise that? We were so far doing just CA policies and suprised that it was sometimes still working unlimited (may be we were just too inpatient).

Thank you
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2abda5-9273-1a56-91b6-e4e77d5706b0
* Version Independent ID: 6a85f2a5-b892-55f7-b49a-4ab15f1e8b73
* Content: [Control access from unmanaged devices - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/control-access-from-unmanaged-devices)
* Content Source: [SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/control-access-from-unmanaged-devices.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment]
Hello **Alex**, how are you?

About the time it takes to reflect the Conditional Access against the SPO Sites, in my experience could take some time (both enabling and disabling them) so one could think that the changes did not apply while it is just a matter of time.

Said that, if you, for example, limit a specific site as the article says, you are already changing the property `ConditionalAccessPolicy` of a site, so that is more than just creating CAs.

Please let me know if I understood correctly your inquiry,

Thank you!

**Comment by AlexSchwerzmann** [comment]
Hi
Thanks for the answer - yes, so this implicites that this property is also doing something within SharePoint and if we want the feature working correctly, we need to set the property and enable CA Policies (while CA Policies are set automatically by setting the property)?
Thanks
Alex

**Comment by get-itips** [comment]
Hello Alex, I am not sure if I understand your last comment, as you can see the instructions for _Block or limit access to a specific SharePoint site or OneDrive_ the first step is creating the CA policies and the second is configuring the setting with the PowerShell module for SharePoint, so yes, the complete steps must be run in order to achieve the limit.

And at Tenant level, you can see that is enough as setting `-ConditionalAccessPolicy AllowLimitedAccess`

**Comment by AlexSchwerzmann** [comment]
Hi Andres
Ok, thanks. I think, I got your point. Means for us, creating only the CA won't be enough to make sure, SharePoint shows eg. up with the information banner or hides the download button.
Regards
Alex
