### ISSUE TITLE
Unable to increase Onedrive storage from 1tb to 5tb

### ISSUE THREAD

**Issue by robinpoulose1** [MicrosoftDocs/OfficeDocs-SharePoint#3203]
Unable to increase Onedrive storage from 1tb to 5tb  for small business plan ,Admin center still shows 5tb and when we switch to org storage nothing happens.
![image](https://user-images.githubusercontent.com/17806101/156917241-31dfc4c4-3a99-428f-b465-40c098a90958.png)

https://docs.microsoft.com/en-us/onedrive/set-default-storage-space

"If your organization has a qualifying Microsoft 365 subscription and five (5) or more users, you can change the storage space to more than 5 TB. To discuss your needs, contact Microsoft support. You must assign at least one license to a user before you can increase the default OneDrive storage space."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0252c106-56e3-96be-5935-ad8aa488e9bd
* Version Independent ID: 901c0c99-c360-3db1-42bc-35f4c70da8b3
* Content: [Set the default storage space for OneDrive users - OneDrive](https://docs.microsoft.com/en-us/onedrive/set-default-storage-space)
* Content Source: [OneDrive/set-default-storage-space.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/set-default-storage-space.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by Archlogic** [comment]
What was your solution, if any? We encountered the same problem except our limit was silently and unexpectedly reduced from a previous setting of 5 TB to 2 TB and then to 1 TB when attempting to set it back to 5, resulting in 200% quota usage. We contacted Microsoft and were informed we'd need to pay $0.25/GB just to get back to the 2 TB threshold, so $256/month unexpected extra cost and then more as storage grew further. Needless to say, we didn't find this answer acceptable, especially in light of documentation that clearly states otherwise. Currently it's in escalation but it's looking like it'll take at least two business days to resolve, assuming that it is. Frustrating experience overall, especially since they did this sort of thing before when it was called SkyDrive, but in that case it was free accounts that were affected and at least they made an announcement. This current situation feels like an outright shakedown.

**Comment by robinpoulose1** [comment]
> 

As per my research this is affected to all small business plan and after assigning OneDrive for business plan 2 license issue is getting resolved. 
I have request to update the article with the storage details for small business
https://github.com/MicrosoftDocs/OfficeDocs-O365ServiceDescriptions/issues/662#issuecomment-1061991145

**Comment by Archlogic** [comment]
Thank you for your quick reply. I saw references to "plan 2" during my research and wondered what that was.

$0.25/GB is in the "add-on" section under Billing -> Purchase services -> Find more add-ons in Purchase services. On second look, it mentions neither OneDrive nor SharePoint, just "extra file storage".
![FireShot 20220309 174204](https://user-images.githubusercontent.com/9909733/157553679-8455590f-0536-441a-bfbd-6a4a99980fe2.png)

Since my previous posting I've been informed by Microsoft that, apparently, all plans, including E3, E5, and "Plan 2" are 1TB with $0.25 GB/month extra. I've escalated further but it's seeming less and less promising.

**Comment by Archlogic** [comment]
After speaking with multiple Microsoft representatives, it turns out that "SharePoint (Plan 2)" supports the desired behavior:

![SharePoint_Plan_2](https://user-images.githubusercontent.com/9909733/157570413-3d02740d-ea86-45f5-87d5-4232d1daba4e.png)

That said, the verbiage in the pop-up box is the exact same as was with the previous plan when that was set up, so I'm not sure how "sticky" these terms are. In any case, that's probably outside the bounds of this thread. Thanks again for the heads-up on where to look.

**Comment by ronssssss** [comment]
This question is about the same issue
https://answers.microsoft.com/en-us/msoffice/forum/all/microsoft-365-onedrive-1tb-limit/60c27695-849d-476e-845c-178da8e174ac?messageId=dfd43e9e-aa6e-4a9b-9f7d-0de29e2a7e16 
.
They eventually got a reply from MS saying that they had (dis)"Improved" the license terms down to 1TB for most users. There is a onedrive license you can buy, "OneDrive for Business Plan 2" 
https://www.microsoft.com/en-us/microsoft-365/onedrive/compare-onedrive-plans?activetab=tab:primaryr2 
for $120 per year per user ON TOP of the 365 Business subscription, to get "unlimited storage" (right, we've heard that line of b***S*** before, 2016 "unlimited" onedrive for consumer 365 ... ). 
.
great scam
