### ISSUE TITLE
Customers shouldn't be referred to Mover.io for large google migrations anymore

### ISSUE THREAD

**Issue by ed-roberts** [MicrosoftDocs/OfficeDocs-SharePoint#3204]
I cannot make a Google Workspace connector in Mover.io, so I shouldn't be referred there.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b62f24-44b9-731f-f143-6a05fa1da328
* Version Independent ID: 15452c1d-d06c-e8f5-9b87-b5fdd0f375ab
* Content: [Migration Manager Google FAQs - Migrate to Microsoft 365](https://docs.microsoft.com/en-us/sharepointmigration/mm-faqs-google)
* Content Source: [migration/mm-faqs-google.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-faqs-google.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @ed-roberts Ed, I am looking into this.

**Comment by tiburd** [comment]
@ed-roberts 
Hi, Ed,

While we're working on this issue, we notice that you are a Microsoft employee. 

At your earliest convenience, please complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

Thank you!

**Comment by get-itips** [comment]
Update to the article is on the way, thanks for the feedback @ed-roberts

**Comment by tiburd** [comment]
The updated article is published, so I'm closing this issue.
Thank you!
