### ISSUE TITLE
OneDrive app not available while create conditional access policy

### ISSUE THREAD

**Issue by jaganpt** [MicrosoftDocs/OfficeDocs-SharePoint#3239]
OneDrive app is not available to enable conditional access while create conditional access policy. Please find the below snap shot for the same. 

![image](https://user-images.githubusercontent.com/78982760/162473354-5afc4f48-7936-4bef-b876-56f03c294ecf.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd1a047-ff5f-48bd-1a9a-87024d3cbe70
* Version Independent ID: 23ae844e-35df-0d4f-50d5-021a5ba9bdf9
* Content: [Enable conditional access support in the OneDrive sync app - OneDrive](https://docs.microsoft.com/en-us/onedrive/enable-conditional-access)
* Content Source: [OneDrive/enable-conditional-access.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/OneDrive/enable-conditional-access.md)
* Service: **one-drive**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by adeejoseph** [comment]
Hi @jaganpt, thanks so much for bringing this to our attention. Please ensure that you've reported the problem following the steps outlined here: https://docs.microsoft.com/en-us/onedrive/enable-conditional-access#reporting-problems. This will allow you to create a ticket that can be tracked so that we may help you further.
