### ISSUE TITLE
We may explain from the beginning that this procedure works ONLY with SharePoint Online!

### ISSUE THREAD

**Issue by JoergSn** [MicrosoftDocs/OfficeDocs-SharePoint#3382]
We may explain from the beginning that this procedure works ONLY with SharePoint Online!

Customers may rely on that, trying it out with any on-prem SharePoint version and it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @mkbond007
* Microsoft Alias: **mabond**

**Comment by CallumCrowley** [comment]
@JoergSn the start of the article does specifically state that the following information is related to Microsoft 365 apps not supporting Internet Explorer 11:

"Last year, we announced that Microsoft 365 apps and services would no longer support Internet Explorer 11 (IE 11). As a result, we no longer recommend View in File Explorer and encourage using the OneDrive sync client."

SharePoint on-premises is not a Microsoft 365 application.

**Comment by JoergSn** [comment]
We from MS know it, but customers are not confused when the information is "really clear".

When reading: "Microsoft 365 apps"...
- Using Word for Windows, such a "Microsoft 365 app", right?
- Using Word together with SPO, steps to use Explorer View are clear enough
- Using Word together with SharePoint on-prem, steps to use Explorer View, customers are irritated, trying, not working, Case with support.

It does not explain why the steps in this article are not working together with SharePoint on-prem.

**Comment by CallumCrowley** [comment]
I don't work for Microsoft but I do know that SharePoint on-premises is not part of Microsoft 365's cloud offering.

Microsoft 365 does come with it's own suite of desktop apps specifically to be used with Microsoft 365 subscriptions. So yes, Word does have a M365 version.

The article is about Microsoft 365 apps and SharePoint on-premises simply isn't a Microsoft 365 app. That's why the steps don't work for on-premises SharePoint. The article also makes many references to SharePoint Online specifically (notably no other version of SharePoint).

The article itself is placed in the Microsoft Docs section that is dedicated to [SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/introduction).

**Comment by JoergSn** [comment]
We can explain it to customers, no worry.
