### ISSUE TITLE
Reindex Site/List - How to check status

### ISSUE THREAD

**Issue by fowl2** [MicrosoftDocs/OfficeDocs-SharePoint#3424]
It would be great if this document included some information on how to tell when a reindex is completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d18cdf74-1e86-aa79-3282-69ffc9cdd282
* Version Independent ID: 39cea6c4-be38-1908-7815-aa9ee552cedf
* Content: [Manually request crawling and reindexing of a site, a library or a list - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/crawl-site-content)
* Content Source: [SharePoint/SharePointOnline/crawl-site-content.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/crawl-site-content.md)
* Service: **sharepoint-online**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by get-itips** [comment]
Hello @fowl2 James,
I think that is not currently available.
Thanks,

**Comment by get-itips** [comment]
@scanum

**Comment by Amshaei** [comment]
* I am writing this with a stern yet empathetic tone *
This needs to be reopened in my opinion. There needs to be some form of status checking and the SharePoint community has been asking for years.
Legitimately all that I, and so many others, want is something like an email or a notification that says "Site Crawl in Progress" and then a "Site Crawl Completed."
That is it.
We just want any type of confirmation that our actions are being processed, or, at the very least, queued.

I keep just seeing posts pointing to other posts and issues.

Can we have a real reason why this isn't possible? It has been an issue since before 2018.  Where can I request this where it will be seen?
