### ISSUE TITLE
Would really like more for this article.

### ISSUE THREAD

**Issue by jasonwbaxter1990** [MicrosoftDocs/OfficeDocs-SharePoint#343]
Hi , Please can we have more information on this topic . As an example How long would it take to migrate content from the file stream to the database , and vice versa. Is the webapplication /database still online or is it locked ?
How do you tell if the migration is progressing ? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad631f70-2d88-9ebd-e822-27e7bd16054f
* Version Independent ID: 297ee8a1-9479-f03d-167b-cf7fe236c040
* Content: [Migrate content into or out of RBS in SharePoint Server](https://docs.microsoft.com/en-us/SharePoint/administration/migrate-content-into-or-out-of-rbs)
* Content Source: [SharePoint/SharePointServer/administration/migrate-content-into-or-out-of-rbs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/migrate-content-into-or-out-of-rbs.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment]
@jasonwbaxter1990 Thank you for this feedback

I will get these questions over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment]
@jasonwbaxter1990 The amount of time it takes varies due to factors such as the amount of content and the performance of the hardware so no number can be provided. There is no lock on the database but this isn't something you'd want to perform during business hours due to the high I/O needed for the database and target file system.

With that being said, if you're using SharePoint 2016 or 2019, I'd strongly recommend you not use RBS. RBS was designed for a SQL Express scenario which these products do not support. RBS has a few draw backs, such as an absolute database size (remember the database size is a combination of database physical size + filestream content) and maintenance of the RBS store.

**Comment by tseward** [comment]
See https://docs.microsoft.com/en-us/sharepoint/administration/maintain-rbs.

**Comment by tseward** [comment]
@jasonwbaxter1990 I do not believe there is any way to monitor the export progress from the content database to file system.
