### ISSUE TITLE
German Translation not complete

### ISSUE THREAD

**Issue by HansBrender** [MicrosoftDocs/OfficeDocs-SharePoint#3466]
The german translation of the following page is not complete

US page https://learn.microsoft.com/en-us/sharepoint/
German translation https://learn.microsoft.com/de-de/sharepoint/
The section It Professionals do not include the word "OneDrive" in the translated page
MY blog post about it: https://hansbrender.com/2022/10/10/from-docs-to-learn/

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [249517](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/249517)

I'm closing this issue because the Global Services team will handle it from here.

cc: @scanum

**Comment by tiburd** [comment]
Reported as resolved.
