### ISSUE TITLE
Delete a deleted site

### ISSUE THREAD

**Issue by BlandinePinto** [MicrosoftDocs/OfficeDocs-SharePoint#352]
Can not delete a deleted site

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d19f5be-8567-336b-cc14-357b20278585
* Version Independent ID: f82afd3a-5e89-fbc2-564a-c49a507de22a
* Content: [View and restore deleted sites in the new SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/view-and-restore-deleted-sites-in-new-admin-center)
* Content Source: [SharePoint/SharePointOnline/view-and-restore-deleted-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-and-restore-deleted-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by Eickhel** [comment]
Hi,

For now, you can do it through PowerShell:
https://docs.microsoft.com/en-us/powershell/module/sharepoint-online/remove-spodeletedsite?view=sharepoint-ps

**Comment by caralynn** [comment]
I am having issues with deleted sites showing back up.  Is this a retention issue?  I deleted sites in the "Active Sites" list using the GUI.  Those sites then move to the "Deleted Sites" list, but the next day, the sites return to the "Active Sites" list.  I must be doing something wrong.

**Comment by oker31** [comment]
I have the same problem. Deleted sites shows up the next day in active sites.

**Comment by AndreaBarr** [comment]
@BlandinePinto Thank you for this feedback

I want to make sure this deleted sites that aren't deleting gets handled the best way possible. I want to get you and anyone else that is having this issue over to Support since they have more resources than we do here to find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
