### ISSUE TITLE
OneDrive "Files On-Demand" setting greyed out in client when policy is set

### ISSUE THREAD

**Issue by Wardrop** [MicrosoftDocs/OfficeDocs-SharePoint#3633]
Per the OneDrive policy documentation, the description for the OneDrive "Files On-Demand" setting states:

"If you enable this setting, new users who set up the sync app see online-only files in File Explorer, **by default.**"

This implies that enabling this option will default "Files On-Demand" to "On", but will allow the user to change it as required (which is the behaviour I wanted). In practise, this policy forcefully enables this policy and doesn't allow the user to change it.

Is this a documentation issue, or is this a bug within the OneDrive client that isn't allowing the user to override the policy "default"?

If someone could also tell me how to set OneDrive to default this to on but allow it to be changed, that'd be very handy. I haven't been able to determine where OneDrive stores this setting if set outside of the policy.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34f99f40-4400-1726-ad6b-a285d8cb8b9f
* Version Independent ID: 49f1c421-03b0-480d-1d82-d8ccdf664bd3
* Content: [Use OneDrive policies to control sync settings - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/use-group-policy)
* Content Source: [SharePoint/SharePointOnline/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
@Wardrop 
if a user syncs f.e. a new document library, all files will be synced with the status : Cloud Only.
if the user clicks on a file, the "Content"  will be downloaded, the status changed to local available, the assosited App opend the file... The User can work with the file

The User always can changed it Status "Local available" or "Always available"
The user can do it alos for folders and change the folder and the files in it to the Status

But If this user wnat to sync another document library, thee files are synced with the status: Cloud Only,, because the adminstrator has set the GPO to this status. 

The User cannot change/Override the GPO.
There are other GPOs for Onedrive, that may change time based all "Local available" files back to "Cloud  Only", to keep the harddic clean.
To ovoid this behavior of the GPO, the iuser should set the status to "Always avalable"

**Comment by scanum** [comment]
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
