### ISSUE TITLE
Production Update Cycle

### ISSUE THREAD

**Issue by Manohar-Pusala** [MicrosoftDocs/OfficeDocs-SharePoint#3824]
[Enter feedback here]
I believe there's a typo in the update cycle frequency. It is mentioned as 1-2 times per week for both insider and production cycle.
I guess it is every 2-4 weeks for production cycle.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2cfa335a-deb6-2ef2-6232-1347984121e1
* Version Independent ID: e0f5b223-3d5b-1415-06e8-6db004b92320
* Content: [The OneDrive sync app update process - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/sync-client-update-process)
* Content Source: [SharePoint/SharePointOnline/sync-client-update-process.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sync-client-update-process.md)
* Service: **one-drive**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by HansBrender** [comment]
so in the past it was. But  since  several months: Insiders 2 times a week, Production weekly. 
See here the versions on my [Blog](https://hansbrender.com/versionen/)
So I receive an Insider Update  on friday...  
I prepare for the weekend
Weekend 2 days
Monday  : full Email box 1 day
Tuesday:  a new version arrived.

When should I test the version?
I havle talk to Microsoft Product Group, that this malke no sense.
We will see, what happens in the future

**Comment by get-itips** [comment]
Hello, given that the article is reflecting current frequency I believe there is no update / fix to the article required.
Thanks both
