### ISSUE TITLE
Missing information and grammatical errors

### ISSUE THREAD

**Issue by stephenc01** [MicrosoftDocs/OfficeDocs-SharePoint#4062]
Choose Select file. Navigate to your mapping .csv file and select. -> and select what?
The file will not be validated, and once migration cannot be changed. -> once migration what? started? stopped?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d143ee1d-cd70-f781-b4ac-8a75095c92bb
* Version Independent ID: 96098fa9-da22-d75c-223d-8c3d85295342
* Content: [Step 5: Map Box identities with Migration Manager - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/mm-box-step5-map-identities)
* Content Source: [migration/mm-box-step5-map-identities.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/mm-box-step5-map-identities.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Thanks for your feedback

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!
