### ISSUE TITLE
Supporting screenshots needed

### ISSUE THREAD

**Issue by alleng365** [MicrosoftDocs/OfficeDocs-SharePoint#4075]
there are no supporting images of the outcome of following the steps outline in this article. that would help understand the logic behind this. New users will find the explanation confusing. A screenshot of the navigation at each level will let individuals know if the steps were a. done correctly and b. if these steps are accomplishing what they want.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c98d42c3-a275-25a1-efbf-03a383c511c1
* Version Independent ID: 7de4ec5f-4a1d-651f-1ace-6d3f62cbf89a
* Content: [Associate a hub site to another hub site in the SharePoint admin center - SharePoint in Microsoft 365](https://learn.microsoft.com/en-us/sharepoint/hub-to-hub-association#How%20hub%20to%20hub%20associations%20work)
* Content Source: [SharePoint/SharePointOnline/hub-to-hub-association.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/hub-to-hub-association.md)
* Service: **sharepoint-online**
* GitHub Login: @MattEEvans
* Microsoft Alias: **matteva**

**Comment by get-itips** [comment]
Hello @alleng365 
How are you?
The article already includes some screenshots where the options in the instructions can be seen, do you still feel a screenshot of every step would be required?
Thank you,

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
