### ISSUE TITLE
Important note is note quite accurate or clear

### ISSUE THREAD

**Issue by CBrasga** [MicrosoftDocs/OfficeDocs-SharePoint#4101]
The "Important" note is a little misleading. "This setting is only applicable to Active Directory domains. It does not apply to Microsoft Entra domains." As it does effectively block OneDrive on syncing Entra only joined devices when enabled.

It may also be worth mentioning the workaround for those with the restriction enabled and Entra joined devices:
https://techcommunity.microsoft.com/t5/sharepoint/onedrive-sync-for-azure-ad-joined-computers/m-p/3630765/highlight/true#M64237

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aff608fe-1f13-ad08-df3e-d2db050b87f8
* Version Independent ID: 32325172-804d-fac1-5deb-9e51ccc6dd75
* Content: [Allow syncing only on computers joined to specific domains - SharePoint in Microsoft 365](https://learn.microsoft.com/en-US/sharepoint/allow-syncing-only-on-specific-domains?WT.mc_id=365AdminCSH_spo)
* Content Source: [SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/allow-syncing-only-on-specific-domains.md)
* Service: **one-drive**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment]
Hello @CBrasga 
How are you?
While I dig into this, can you please detail which version of the OneDrive client are you running? Also, please expand what you exactly did, did you used the _Allow syncing only on computers joined to specific domains check box_ described in this article and entered a 365 Tenant Guid on the text field?

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
