### ISSUE TITLE
Please add more details on Exclude Settings

### ISSUE THREAD

**Issue by martinn79** [MicrosoftDocs/OfficeDocs-SharePoint#4113]
Hi!

Please provide more details and examples on the settings section of the SharePoint Migration Tool for the following settings:

- Filter subsites
- Filter lists and libraries
- Filter content type

"Enter the names of ..." is quite unspecific. How to separate names if there is more than one? And does it want the (probably localized) display name (title) or the 'internal name' or the GUID?

![image](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/assets/36664840/7c58662c-59cd-4d0d-ac3d-ac4af6551679)

**Note:**
There are multiple queries for this topic, all of them marked as Closed without any relevant solution. In fact, the 'resolutions' provided are not even close to the topic. Moreover, nobody took care of author's request following the invalid closure of the query (as an example ID #2052 https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2052).

**Comment by officedocspr5** [comment]
To make it easier for you to submit feedback on articles on learn.microsoft.com, we're transitioning our feedback system from GitHub Issues to a new experience. 

As part of the transition, this GitHub Issue will be moved to a private repository. We're moving Issues to another repository so we can continue working on Issues that were open at the time of the transition. When this Issue is moved, you'll no longer be able to access it.

If you want to provide additional information before this Issue is moved, please update this Issue before December 15th, 2023.

With the new experience, you no longer need to sign in to GitHub to enter and submit your feedback. Instead, you can choose directly on each article's page whether the article was helpful. Then you can then choose one or more reasons for your feedback and optionally provide additional context before you select **Submit**.

Here's what the new experience looks like.

**Note**: The new experience is being rolled out across learn.microsoft.com in phases. If you don't see the new experience on an article, please check back later.

First, select whether the article was helpful:

![Image showing a dialog asking if the article was helpful with yes and no answers.](https://learn.microsoft.com/Office/media/internal/new-feedback-yes-no.jpg)

Then, choose at least one reason for your feedback and optionally provide additional details about your feedback:

| Article was helpful | Article was unhelpful |
|:--|:---|
|![Image showing a dialog asking how the article was helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-helpful.jpg) | ![Image showing a dialog asking how the article wasn't helpful with several options.](https://learn.microsoft.com/Office/media/internal/new-feedback-unhelpful.jpg)|

Finally, select **Submit** and you're done!

**Comment by martinn79** [comment]
@scanum I have few questions:
Why is this issue Closed and who said that this issue is Completed?
Where is the link to a follow-up issue 'to another repository so we can continue working on Issues that were open at the time of the transition'? 
Why are you posting a non-sense information about how to submit an issue instead of providing really valuable information?
