### ISSUE TITLE
Clarification - default user mapping file used

### ISSUE THREAD

**Issue by nalhemyariirexorg** [MicrosoftDocs/OfficeDocs-SharePoint#415]
What does 'the default user mapping' mean in this article, when migrating files from a network share to SharePoint Online, the account I used is all over the place as modified by/Created by, i was hopping to see the author of word, excel, etc.. there instead.

Second question, can we assign a default user for those files that the tool cannot extract their ownership, this can be useful when migrating Photos, pdf files, etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8379014-03ff-3ab5-aa1f-5d9c3a02be68
* Version Independent ID: cfabc646-70ea-6b24-7d16-ea0955479aa5
* Content: [Create a user mapping file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/create-a-user-mapping-file-for-data-content-migration)
* Content Source: [migration/create-a-user-mapping-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/create-a-user-mapping-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment]
@nalhemyariirexorg Thank you for this inquiry

I am not sure how to answer your questions about the owners of these files. Let me get this over to the SharePoint team for investigation so we can get some clarification for you. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by nalhemyariirexorg** [comment]
Thank you Andrea, and while we are on it, just checking if there is a limit for the number of records SID->UPN by the tool, my csv file is about 15k lines

**Comment by AndreaBarr** [comment]
@nalhemyariirexorg  no problem. They will see your added on comment when the investigate this. They will comment when they have more information for you. Thank you for your patience with us.

**Comment by tseward** [comment]
@nalhemyariirexorg Defaut user mapping would be the map between the on-prem account and the account found in O365. Modifying this will be useful if you're not sync'ing Active Directory with Azure AD using AAD Connect or you want to otherwise override the default mapping if you are sync'ing via AAD Connect. For example, while CONTOSO\tim might map to tim@contoso.onmicrosoft.com, perhaps you want to map CONTOSO\tim to jane@contoso.onmicrosoft.com.

Typically in most companies who have an on-prem AD presence they will be using AAD Connect so this would be largely unnecessary to modify.

Like other migration tools, SPMT will pick up NTFS file attributes such as who created/modified the file as well as timestamps. I'm not aware of a 3rd party tool that will take document properties and map those into Created By/Modified By etc.

Upper bounds should be quite high and would be more limited by memory (depending on how the CSV is parsed).

**Comment by sagaracharya21** [comment]
Hello,

Does this tool support to migrate quickparts embedded in document ?

Thanks 
Sagar Acharya

**Comment by AndreaBarr** [comment]
@tseward Could you please answer the above inquiry?

**Comment by tseward** [comment]
@sagaracharya21 It will migrate the content (text) present in the quickpart, but the quickpart will not be attached to the library column post-migration.

**Comment by pranatim** [comment]
I am trying to migrate from the file system. I have used the User Mapping file .csv. But Author data from file share not seems to be migrated. Am I missing anything?

**Comment by jamilhaddadin** [comment]
I think @nalhemyariirexorg has asked another question which is:

> "Second question, can we assign a default user for those files that the tool cannot extract their ownership, this can be useful when migrating Photos, pdf files, etc..."

My case is migrating from SharePoint 2013 to SharePoint online, some users are not part of the AD anymore, so there should be a place to add a "default user" for this, is that available?

**Comment by jamilhaddadin** [comment]
@tseward I would love to hear your view on that please :-)
