### ISSUE TITLE
Sharepoint Issues

### ISSUE THREAD

**Issue by wclarke77** [MicrosoftDocs/OfficeDocs-SharePoint#432]
Microsoft lost all subsite data.  Need to restore from a 3 year old back up cmp file.  Microsoft is NO helped!!

**Comment by kenwith** [comment]
@wclarke77 - This Issue list is for the docs for SharePoint but I completely feel your pain. I was a SharePoint admin for years before starting here at Microsoft. I am not sure how much I can as I focus on the docs and the community in these GitHub repos but I am here to do whatever I can to help.

I think the first step is to get a support ticket open so that the group can escalate your issue. 

If you are using SharePoint Online then you can open a service ticket in your tenant. Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you are using SharePoint Server (on premises) there should be a support number for your organization.

Again, I am here to help however I can and I can help reach out to people internally too but to get things started off if you could open a service ticket.

I am going to close this issue on this list so it doesn't get lumped in with 'content issues' and you can email me directly as you work through to get this resolved. My email is on my GitHub profile: https://github.com/kenwith
