### ISSUE TITLE
Wrong minroles listed for incoming email support?

### ISSUE THREAD

**Issue by cloudgreen** [MicrosoftDocs/OfficeDocs-SharePoint#596]
Under the "About incoming email" paragraph, there are 5 minroles listed that can be used with the incoming email feature: Application, Application with Search, Front-end, Search and Custom.

But according to the document below (#1), the only minroles containing the incoming email service are Application, Application with Search and Single-server farm (and implicitly the "Custom" role). I suppose Front-end and Search should be removed from the list on this page?

#1
Description of MinRole and associated services 
https://docs.microsoft.com/en-us/sharepoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0b1f842-b2ca-71a7-a063-d26ceaab8ffe
* Version Independent ID: 02434425-3bbb-127e-72e6-63548d4d5b57
* Content: [Plan incoming email for a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/incoming-email-planning)
* Content Source: [SharePoint/SharePointServer/administration/incoming-email-planning.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/incoming-email-planning.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by TroyStarr** [comment]
Hi @tseward, do you think we should also include the "Single-Server Farm" server role in this list?

**Comment by tseward** [comment]
@TroyStarr yes. Will update the article.

**Comment by tseward** [comment]
@TroyStarr spoke too soon. I would say that we should probably remove SSF from https://docs.microsoft.com/en-us/sharepoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016. It's not designed for production usage scenarios and runs all roles... not much point in listing it.

**Comment by TroyStarr** [comment]
Hmm, I dunno…  We know that Single-Server Farm runs all* services, but that may not be obvious to people who aren't yet familiar with MinRole and are looking to understand it better.  I think it would be useful to continue listing SSF in the [Description of MinRole and associated services in SharePoint Servers 2016 and 2019 article](https://docs.microsoft.com/sharepoint/administration/description-of-minrole-and-associated-services-in-sharepoint-server-2016) (and the list in the [incoming e-mail article](https://docs.microsoft.com/sharepoint/administration/incoming-email-planning)), but we can always add a note to remind people that we don't recommend using this role for more than dev/test/pilot/"limited production" environments.

\* The one exception would be third party services that haven't been recompiled to be MinRole aware.  Those services won't run on SSF because they haven't indicated which server roles they're compatible with, so they would only run on the Custom server role.

**Comment by tseward** [comment]
OK, sounds good. I added the commit to show SSF in the incoming email article. Is there something better we can say other than "limited production"? There will be questions about what "limited" means in Microsoft's eyes.

**Comment by TroyStarr** [comment]
Here's the official description we're using in the [Planning for a MinRole server deployment in SharePoint Servers 2016 and 2019](https://docs.microsoft.com/sharepoint/install/planning-for-a-minrole-server-deployment-in-sharepoint-server) article:

> Service applications, services, and components required for a single-server farm belong on a server running the Single-Server Farm role. Use this role for development, testing, and limited production tasks.

I realize it's not very specific, but there could be a lot of factors that go into what that means. (number of users, amount/size of data, requests/sec, etc.)  I'm inclined to leave it at that unless you think it's important to put a specific number in there.

**Comment by AndreaBarr** [comment]
@cloudgreen the article update has been reviewed and merged so you should see that reflected within the next day or so. I am going to close this issue at this time. If this article updated doesn't resolve your issue please re-open this issue.
