### ISSUE TITLE
SQL 2016 Support

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-SharePoint#61]
Please elaborate on the statement "SQL Server 2014 is the only version of RBS that is supported by SharePoint Server 2016." Are there any plans to provide this functionality in SQL 2016 or later?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 517b9ac9-dc73-7eec-1e4c-d9b0c8984f83
* Version Independent ID: 85db03bc-cc90-b36f-d08e-4203a86eb505
* Content: [Overview of RBS in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/administration/rbs-overview)
* Content Source: [SharePoint/SharePointServer/administration/rbs-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/rbs-overview.md)
* Service: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by Techwriter40** [comment]
@bentoncity for awareness

**Comment by bentoncity** [comment]
Dean, you'll need to check with the SQL team as they own Remote Blob Storage.

**Comment by tseward** [comment]
Another point worth considering is that RBS for SharePoint was originally designed around SQL Express limitations. And of course RBS for SharePoint has some fairly significant limitations for SharePoint content sizing.

Strongly consider avoiding it with SharePoint 2016+ since SQL Express isn't an option. Or use a 3rd party RBS solution.
