### ISSUE TITLE
SharePoint Migration Tool - ISO files - Disk Space Error

### ISSUE THREAD

**Issue by miket4057** [MicrosoftDocs/OfficeDocs-SharePoint#71]
I have been testing the SharePoint Migration Tool, the version prior to v2.0.99.0 worked fine when migrating a set of data from a file share to a OneDrive for Businesssite for 1 user.  The source content has not changed but now I get an error "Disk space is not   enough."  It stops each time on a 4 GB ISO file.  I tried to migrate again and set the tool to ignore ISO files and it still fails with the same error. 
![image](https://user-images.githubusercontent.com/39199210/39938600-77b900b4-5521-11e8-937b-e7f64512f444.png)

When I run the tool in scan only mode it does not find any errors.

The server that I am running the tool from has plenty of disk space and the user has plenty of space on the OneDrive for Business site.  Any ideas?

**Comment by kenwith** [comment]
@miket4057 - I am sorry this has gone stale in the documentation comments. I am hoping this was fixed in recent release. If not, the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP.

Based on outcome let me know if it is something that can be called out in the docs.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
