### ISSUE TITLE
Docs don’t line up to my experience 

### ISSUE THREAD

**Issue by ajhstn** [MicrosoftDocs/OfficeDocs-SharePoint#782]
When sharing to a work account from another Office365 subscription the user was unable to signin with its work account, instead it was treated as a user requiring a email code each time.

When sharing with a Microsoft Account, the same as above.

When sharing to a gmail account, the same as above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6cadc974-5434-4647-6480-996c1e40a2f8
* Version Independent ID: 7953c446-e5ac-6a46-4ab4-7acd4b75f3b0
* Content: [External sharing overview](https://docs.microsoft.com/en-us/sharepoint/external-sharing-overview#feedback)
* Content Source: [SharePoint/SharePointOnline/external-sharing-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/external-sharing-overview.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by lindspea** [comment]
@ajhstn Thank you for reaching out and helping improve MS Docs.  I have the team looking into this.  I'll have a reply for you soonest.

**Comment by kaarins** [comment]
@ajhstn Thanks for contacting us. I just recently updated this article and added screen shots. When you share with someone who has a gmail address, the person will always have to use a code. When you share with someone who has a Microsoft account (hotmail.com, live.com, outlook.com), the person should be able to sign in and be added to the directory. When you share with someone who has a work or school account in Office 365 for another organization, it varies. They will get a code the first time. They might be able to sign in after that, or they might have to use a code each time. The team is working on this.

**Comment by cdegroote** [comment]
The term "Microsoft Account" is kind of misleading. In my experience sharing without a code is ony possible when using a work/school Office 365 account or with users with at hotmail / live / outlook.com account which is not the same as a Microsoft account since ayone can register for a Microsoft account using his private e-mail address at https://account.microsoft.com. 
However user experience for those Microsoft accounts remains same: you need to login with the code and do not get the same functionality as when logged in with the work/school/hotmail account (e.g. setting alerts).
I would suggest to refer to hotmail/live/outlook when using the term Microsoft account in the docs
