### ISSUE TITLE
Server OS

### ISSUE THREAD

**Issue by vo5tr0** [MicrosoftDocs/OfficeDocs-SharePoint#819]
Is Windows Server 2016 or 2019 especially in an RDS environment supported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation#feedback)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by pyoungberg** [comment]
Would like to know as well. This seems like a direct fix for the "OneDrive not supported in RDS environments" issue - hoping that's the case!

**Comment by smith-ll** [comment]
Keen to know this aswell. Seems like it should have been an obvious thing to support what with roaming profiles etc

**Comment by jhochwald** [comment]
It’s not working as expected on an RDSH Host. You can install it as described, you can configure it as described... when you log off and back in oneDrive will throw the error that the OneDrive Folder (that you synced before) is not found.
The OneDrive Folder is not synced to the central profile store.

**Comment by gacarini** [comment]
I've updated the wording on the supported OS version to link to our min requirements page since the per-machine install is supported on all supported Windows versions, including service. Regarding Windows Server 2019, stay tuned but when we're ready to declare it officially supported, it will be added to that page I linked to. 

In terms of VDI environments, the statement on this page is still accurate: https://support.office.com/en-ie/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa#windowsspecific. As you can see it calls out that for non-persistent environments, OneDrive is supported on WVD (which in fact uses the per-machine client out-of-the-box) and we're working on updating the documentation to mentioned environments using FSLogix. Per-machine OneDrive only changes how/where the client is installed. 

Does that help?

**Comment by vo5tr0** [comment]
Thank you, that helps a lot! I am looking forward to the final release and the FSLogix Update :)
