### ISSUE TITLE
What about the OneDrive client that comes with Windows 10?

### ISSUE THREAD

**Issue by knutale** [MicrosoftDocs/OfficeDocs-SharePoint#823]
... will it change to per-machine ODFB client as well? If so, when (which Feature Upgrade) will it happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 087b8ed9-0b08-88a2-825f-727915801554
* Version Independent ID: afd3bb47-f8a7-d1eb-a790-ff49c0794d2f
* Content: [Install the sync client per machine](https://docs.microsoft.com/en-us/onedrive/per-machine-installation)
* Content Source: [OneDrive/per-machine-installation.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/per-machine-installation.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by NeighborGeek** [comment]
OneDrive client per-machine install is an option, the default is still Per-User.  The OneDrive client that ships with Windows 10 will still use the default, installing once for each user.

The OneDrive client is included in Windows 10, but not in the sense that it's pre-installed or integrated into the OS. 
 The way that the OneDrive client is included is that OneDriveSetup.exe is included in %windir%\SysWOW64, and that setup program runs for each user after they log in for the first time.  Each feature update for Win10 includes the current copy of that setup file, but since the OneDrive client is updated so frequently, that copy of the setup file on a computer quickly becomes outdated.  One of the first things OneDrive does after setup is check for a newer version of the client, and if one is available it downloads and installs the latest version.  This ensures that even though the setup file included with windows is older, the installed copy of OneDrive should always be kept up to date.  

It's possible that in a future update MS may make the OneDrive client install per-machine by default, in which case the client included with Win10 would likely use the per-machine install, but they've not yet given indication that they plan to do so.  Understandable, considering that this optional install method is only now entering public preview.

**Comment by scanum** [comment]
@knutale  Thank you for submitting this feedback.

From our understanding the issue has been resolved. If you feel it hasn't been resolved please re-open this issue.

**Comment by scanum** [comment]
@officedocsbot close
