### ISSUE TITLE
OneDrive for Mac "Turn on files on-demand" not working

### ISSUE THREAD

**Issue by j-drew** [MicrosoftDocs/OfficeDocs-SharePoint#839]
In OneDrive on a Mac running Mojave I am trying to activate Files On-Demand. Every time I click "Turn on files on-demand" OneDrive crashes and reboots but the option never activates. Is there a script I can run to force files on demand to activate? It should simply be on by default.
 
I am syncing a OneDrive of about 800Gb but the iMac only has 500Gb hard drive so it is essential that I get files on-demand working before OneDrive completes syncing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 116a7d33-b79a-f07d-b9de-d032d805c8d5
* Version Independent ID: 94908ca2-5edc-eb8c-b8a2-72cf61969dc7
* Content: [Set Files On-Demand states](https://docs.microsoft.com/en-us/OneDrive/files-on-demand-mac#feedback)
* Content Source: [OneDrive/files-on-demand-mac.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/files-on-demand-mac.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@j-drew  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by MartinBCol** [comment]
Did you get a resolution for this issue?  I have the identical symptom.

**Comment by j-drew** [comment]
My recent experience, OneDrive for Mac _should_ automatically activate file-on-demand by default. So this issue seems to have been fixed. Make sure you have the latest Mac OS and OneDrive version as well.

**Comment by cuong-tran** [comment]
Mine macbook, running 2 account at same time: 1 personal & 1 is Office360 subscribed.
The account Office360 has File On-Demand turned on and working.
While at same time, same machine, same user, Personal account crashes every time I try turn on File On-Demand.
Weird.

**Comment by cuong-tran** [comment]
> Did you get a resolution for this issue? I have the identical symptom.

I had same issue. Thing is I have 2 account linked at same time, 1 with File On-Demand working while the other crashes everytime trying to turn on File On-Demand.

Found out the reason is that I sync to a folder on second drive, not the default boot-up system drive. After unlink account then relink again, keep default folder which OneDrive suggests, File On-Demand works, and turned on automatically.

**Comment by ThomoJames97** [comment]
After finding pretty much nowhere that states the cause for this error message and hence doing some experimenting, I've found the actual cause for it is that on Mac, files on demand **only** works if the drive you are syncing to is APFS formatted. If you're using a Hackintosh and require HFS for the system, **set up an APFS partition and chose that as the OneDrive directory.**

**Comment by ThomoJames97** [comment]
After finding pretty much nowhere that states the cause for this error message and hence doing some experimenting, I've found the actual cause for it is that on Mac, files on demand **only** works if the drive you are syncing to is APFS formatted. If you're using a HFS formatted disk as your primary boot drive, i.e. on Hackintosh, **set up an APFS partition and chose that as the OneDrive directory.**

**Comment by ThomoJames97** [comment]
After finding nowhere with an actual solution and doing some experimenting, I've found the actual cause for it is that on Mac, files on demand **only** works if the drive you are syncing to is APFS formatted. The error message will **only** show if you downloaded OneDrive from the pkg file from Microsoft's website instead of from the Mac App Store, which is dumb. If you're using a HFS formatted disk as your primary boot drive, i.e. on Hackintosh, **set up an APFS partition and chose that as the OneDrive directory.**
